<div class="jumbotron rounded-0 vertical-center bg-dark text-white">
    <div class="container">
        <img src="./assets/img/logo/logo-200px.png" style="margin: 50px 0px; width: 200px !important; height: 200px !important;">
        <h1 class="display-4"><?php echo $page->header; ?></h1>
        <p class="lead text-uppercase">
            <?php echo $page->lead; ?>
        </p>
        <hr class="border-light">
        <p>
            <?php echo $page->author; ?>
        </p>
    </div>
</div>