<div class="static-slider static-slider-type-1" style="background-image:url(assets/img/multipurpose/bg-color.jpg)">
    <div class="container">
        <div class="row justify-content-center ">
            <div class="col-md-8 align-self-center text-center" data-aos="fade-right" data-aos-duration="1200">
                <h1 class="title text-light text-uppercase">Contact</h1>
                <h5 class="text-light font-weight-normal">With Infinite Multipurpose, you can create everything, weather its Landing page, Complete Website, Lead generation or Coming soon etc.</h5>
            </div>
        </div>
    </div>
</div>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Contact 1</h1>
                <h6 class="subtitle">Below is contact. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
	
    <div class="contact1">
        <div class="row">
            <div class="col-md-12">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d63377.1038100461!2d107.50823726635176!3d-6.882339276787305!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e68e44edd0ff515%3A0x31fa17105be7a601!2sCimahi+City%2C+West+Java!5e0!3m2!1sen!2sid!4v1520478241188" width="100%" height="450" frameborder="0" style="border:0"></iframe>
            </div>
        </div>

        <div class="container">
            <div class="row mt-3">
                <div class="col-lg-8">
                    <div class="contact-wrapper">
                        <h5 class="title font-weight-normal mt-0">Quick Contact</h5>
                        <form data-aos="fade-left" data-aos-duration="1200">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <input class="form-control" type="text" placeholder="name">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <input class="form-control" type="email" placeholder="email">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <textarea class="form-control" rows="3" placeholder="message"></textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <button type="submit" class="btn btn-lg btn-danger">SUBMIT</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="detail-wrapper p-5 bg-info" data-aos="fade-right" data-aos-duration="1200">
                        <h3 class="text-white font-weight-normal mb-3">Infinite Headquarters</h3>
                        <p class="text-white">123 456 789
                            <br> info@infinite.com</p>
                        <p class="text-white">Cimahi.
                            <br> Jawa Barat, Indonesia</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Contact 2</h1>
                <h6 class="subtitle">Below is contact. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <div class="contact2" style="background-image:url(assets/img/map-black.jpg);">
        <div class="container">
            <div class="row contact-container">
                <div class="col-lg-12">
                    <div class="card card-shadow border-0" data-aos="fade-up" data-aos-duration="1200">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="contact-wrapper p-5">
                                    <h5 class="title font-weight-normal">Contact Us</h4>
                                    <form>
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <input class="form-control" type="text" placeholder="name">
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <input class="form-control" type="email" placeholder="email">
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <input class="form-control" type="text" placeholder="phone">
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <input class="form-control" type="text" placeholder="location">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <textarea class="form-control" rows="3" placeholder="message"></textarea>
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <button type="submit" class="btn btn-danger btn-lg">SUBMIT</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-4 bg-info">
                                <div class="detail-wrapper">
                                    <h5 class="text-white font-weight-normal mb-3">ADDRESS</h5>
                                    <p class="text-white">Cimahi.
                                        <br>Jawa Barat, Indonesia</p>
                                    <h5 class="text-white font-weight-normal my-3">CALL US</h5>
                                    <p class="text-white">123 456 789
                                        <br> 987 654 321</p>
                                    <div class="round-social light">
                                        <a href="#" class="ml-0"><i class="fab fa-facebook"></i></a>
                                        <a href="#" class=""><i class="fab fa-twitter"></i></a>
                                        <a href="#" class=""><i class="fab fa-youtube"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>