<div class="static-slider static-slider-type-1" style="background-image:url(assets/img/multipurpose/bg-color.jpg)">
    <div class="container">
        <div class="row justify-content-center ">
            <div class="col-md-8 align-self-center text-center" data-aos="fade-right" data-aos-duration="1200">
                <h1 class="title text-light text-uppercase">Footer</h1>
                <h5 class="text-light font-weight-normal">With Infinite Multipurpose, you can create everything, weather its Landing page, Complete Website, Lead generation or Coming soon etc.</h5>
            </div>
        </div>
    </div>
</div>

<section class="bg-gray pt-2 pb-0">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Footer 1</h1>
                <h6 class="subtitle">Below is footer. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
	<div class="footer1 bg-white">
        <div class="topbar">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" data-aos="fade-right" data-aos-duration="1200">
                        <nav class="navbar navbar-expand-lg"> 
                            <a class="navbar-brand d-block d-md-none d-lg-none" href="javascript:void(0);">Footer Navbar</a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footer1" aria-controls="ft1" aria-expanded="false" aria-label="Toggle navigation"> 
                                <span class="fas fa-bars"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="footer1">
                                <ul class="navbar-nav">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="javascript:void(0);">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="javascript:void(0);">About Me</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="javascript:void(0);">Services</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="javascript:void(0);">Blog</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="javascript:void(0);">Work</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="javascript:void(0);">Contact</a>
                                    </li>
                                </ul>
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark text-uppercase" href="javascript:void(0);">
                                            <i class="fas fa-envelope text-danger mr-2"></i>Request a  Free Consultation
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="middle">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <a href="#"><img src="assets/img/logo-multipurpose.png" alt="Infinite Multipurpose" height="50" /></a>
                        <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                        <p>our amazing features list and also our customer services is great.</p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="d-flex mb-2">
                            <div class="mr-3 align-self-top">
                                <i class="fas fa-map-marker"></i>
                            </div>
                            <div class="info">
                                <span class="text-dark d-block">Infinite Head Office</span>
                                <br/>
                                <p>
                                    134, Cornish Building, Some
                                    <br/> Near by area, New York,
                                    <br/> USA - 34556
                                </p>
                            </div>
                        </div>
                        <div class="d-flex mb-3">
                            <div class="mr-3 align-self-top">
                                <i class="fas fa-phone"></i>
                            </div>
                            <div class="info">
                                <span class="text-dark d-block">(+62) 123 4567</span>
                            </div>
                        </div>
                        <div class="d-flex mb-3">
                            <div class="mr-3 align-self-top">
                                <i class="fas fa-envelope"></i>
                            </div>
                            <div class="info">
                                <a href="#" class="text-dark d-block">info@infinite.com</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 m-t-5">
                        <span class="text-dark d-block">Service We Offer</span>
                        <ul class="general-listing two-part mt-2">
                            <li><a href="#"><i class="fa fa-angle-right"></i> Website Design</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Application Development</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Mobile Development</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Search Engine Optimzation</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Digital Marketing</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Website Development </a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> eBook Writing </a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> SaaS base Applications</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Ruby on Rails Development </a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Php Development</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="bottom-bar">
            <div class="container">
                <div class="d-flex">
                    <div class="my-2">© All Rights Reserved by Infinite Multipurpose.</div>
                    <div class="links ml-auto mt-2 mb-2">
                        <a href="javascript:void(0);" class="link p-2"><i class="fab fa-facebook"></i></a>
                        <a href="javascript:void(0);" class="link p-2"><i class="fab fa-twitter"></i></a>
                        <a href="javascript:void(0);" class="link p-2"><i class="fab fa-linkedin"></i></a>
                        <a href="javascript:void(0);" class="link p-2"><i class="fab fa-pinterest"></i></a>
                        <a href="javascript:void(0);" class="link p-2"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray pt-2 pb-0">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Footer 2</h1>
                <h6 class="subtitle">Below is footer. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <div class="footer2 bg-dark">
        <div class="topbar">
            <div class="container">
                <div class="d-flex">
                    <a href="#"><img src="assets/img/logo-multipurpose-white.png" alt="Infinite Multipurpose" height="50" /></a>
                    <div class="ml-auto align-self-center">
                        <span class="text-white">Infinite Multipurpose by O2System</span> © 2018 All rights reserved.
                    </div>
                </div>
            </div>
        </div>
        <div class="middle">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <p class="pt-2">Nullam erat ametam arcu lorme pharetra id risus act sectetur ipsum luctus est ullam erat ametam arcu lorme pharetra id us act sectetur ipsum luctus est. </p>
                        <p>Vestibulum in accumsa maga eds maurise elit tincidunt turpis id semper. </p>
                        <div class="my-3">
                            <a href="#" class="link"><i class="fab fa-facebook"></i></a>
                            <a href="#" class="link"><i class="fab fa-twitter"></i></a>
                            <a href="#" class="link"><i class="fab fa-linkedin"></i></a>
                            <a href="#" class="link"><i class="fab fa-pinterest"></i></a>
                            <a href="#" class="link"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6">
                        <ul class="general-listing">
                            <li><a href="#"><i class="fa fa-circle"></i> Home</a></li>
                            <li><a href="#"><i class="fa fa-circle"></i> Services</a></li>
                            <li><a href="#"><i class="fa fa-circle"></i> Pricing</a></li>
                            <li><a href="#"><i class="fa fa-circle"></i> Case Studies</a></li>
                            <li><a href="#"><i class="fa fa-circle"></i> Blog</a></li>
                            <li><a href="#"><i class="fa fa-circle"></i> Contact Us </a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3 col-md-6 info-box">
                        <div class="d-flex">
                            <div class="mr-3 align-self-top"><i class="fas fa-map-marker"></i></div>
                            <div class="info">
                                <p>
                                    134, Cornish Building, Some
                                    <br/> Near by area, New York,
                                    <br/> USA - 34556
                                </p>
                            </div>
                        </div>
                        <div class="d-flex">
                            <div class="mr-3 align-self-top"><i class="fas fa-clock"></i></div>
                            <div class="info">
                                <span class="d-block">8.00 AM - 6:00PM</span>
                            </div>
                        </div>
                        <div class="d-flex">
                            <div class="mr-3 align-self-top"><i class="fas fa-phone"></i></div>
                            <div class="info">
                                <span class="d-block">(+62) 123 4567</span>
                            </div>
                        </div>
                        <div class="d-flex">
                            <div class="mr-3 align-self-top"><i class="fas fa-envelope"></i></div>
                            <div class="info">
                                <a href="#" class="d-block">info@infinite.com</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="subscribe-box">
                            <p>Nullam erat ametam arcuing lorme pharetra id risus act sectetur ipsum luctus est. </p>
                            <form>
                                <div class="mb-3">
                                    <input class="form-control" placeholder="enter email">
                                </div>
                                <button class="btn btn-danger">SUBSCRIBE</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray pt-2 pb-0">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Footer 3</h1>
                <h6 class="subtitle">Below is footer. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <div class="footer3 bg-dark">
        <div class="topbar container">
            <div class="d-flex">
                <div class="d-flex align-items-center">
                    <a href="#" class="mr-3"><img src="assets/img/logo-multipurpose-white.png" alt="Infinite Multipurpose" height="30" /></a>
                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod <br/>tempor incididunt ut labore et dolore magna ad minim.</span>
                </div>
                <div class="ml-auto align-self-center">
                    <form>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Sign up for updates">
                            <span class="input-group-btn">
                              <button class="btn btn-danger" type="button">Go!</button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="middle container">
            <div class="row">
                <div class="col-lg-3 col-md-6 mb-3">
                    <h6 class="text-white">SERVICES</h6>
                    <ul class="general-listing">
                        <li><a href="#"><i class="fa fa-angle-right"></i> Website Design</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i> Mobile App Development</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i> Search Engine Optimization</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i> Website Development</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-3">
                    <h6 class="text-white">PROJECTS</h6>
                    <div class="d-flex align-items-center mt-3">
                        <div class="thumb mr-2"><img src="assets/img/hello/app-boilerplate.jpg" alt="Infinite Multipurpose" /></div>
                        <div class="blog-text"><a href="#" class="link">Hotel nira inn got bigger heding you ever seen.</a></div>
                    </div>
                    <div class="d-flex align-items-center mt-3">
                        <div class="thumb mr-2"><img src="assets/img/hello/basic-boilerplate.png" alt="Infinite Multipurpose" /></div>
                        <div class="blog-text"><a href="#" class="link">Hotel nira inn got bigger heding you ever seen.</a></div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 mb-3">
                    <h6 class="text-white">BLOG</h6>
                    <div class="d-flex align-items-center mt-3">
                        <div class="thumb mr-2"><img src="assets/img/hello/api-boilerplate.jpg" alt="Infinite Multipurpose" /></div>
                        <div class="blog-text"><a href="#" class="link">Hotel nira inn got bigger heding you ever seen.</a></div>
                    </div>
                    <div class="d-flex align-items-center mt-3">
                        <div class="thumb mr-2"><img src="assets/img/hello/cms-boilerplate.jpg" alt="Infinite Multipurpose" /></div>
                        <div class="blog-text"><a href="#" class="link">Hotel nira inn got bigger heding you ever seen.</a></div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 mb-3">
                    <h6 class="text-white">CONTACT</h6>
                    <div class="d-flex mb-3 mt-3">
                        <div class="mr-3 align-self-top"><i class="fas fa-map-marker"></i></div>
                        <div class="info">
                            <p> 321 Name of Street Avenue,<br/> Country</p>
                        </div>
                    </div>
                    <div class="d-flex mb-3">
                        <div class="mr-3 align-self-top"><i class="fas fa-phone"></i></div>
                        <div class="info">
                            <span class="d-block">(+62) 123 4567</span>
                        </div>
                    </div>
                    <div class="d-flex mb-3">
                        <div class="mr-3 align-self-top"><i class="fas fa-envelope"></i></div>
                        <div class="info">
                            <a href="#" class="link d-block">info@infinite.com</a>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="bottom-bar">
            <div class="container">
                <div class="d-flex">
                    <span class="mt-2 mb-2">Copyright 2017. All Rights Reserved by O2System.</span>
                    <div class="ml-auto mt-2 mb-2">
                        <a href="#" class="link"><i class="fab fa-facebook"></i></a>
                        <a href="#" class="link"><i class="fab fa-twitter"></i></a>
                        <a href="#" class="link"><i class="fab fa-linkedin"></i></a>
                        <a href="#" class="link"><i class="fab fa-pinterest"></i></a>
                        <a href="#" class="link"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray pt-2 pb-0">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Footer 4</h1>
                <h6 class="subtitle">Below is footer. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <div class="footer4 bg-white">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 mb-3">
                    <h5 class="mb-3 font-weight-normal">Address</h5>
                    <p>71 Amsteroum Avenue Cronish Night, NY 35098</p>
                </div>
                <div class="col-lg-3 col-md-6 mb-3">
                    <h5 class="mb-3 font-weight-normal">Phone</h5>
                    <p>
                        Reception : +62 123 4567
                        <br/>Office : +62 235 7890
                    </p>
                </div>
                <div class="col-lg-3 col-md-6 mb-3">
                    <h5 class="mb-3 font-weight-normal">Email</h5>
                    <p>
                        Office : <a href="#" class="link">info@infinite.com</a>
                        <br/>Site : <a href="#" class="link">infinite.com</a>
                    </p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="mb-3 font-weight-normal">Social</h5>
                    <div class="social round-social light">
                        <a href="#" class="link"><i class="fab fa-facebook"></i></a>
                        <a href="#" class="link"><i class="fab fa-twitter"></i></a>
                        <a href="#" class="link"><i class="fab fa-linkedin"></i></a>
                    </div>
                </div>
            </div>
            <div class="bottom-bar">
                <div class="row">
                    <div class="col-md-12">
                        <nav class="navbar navbar-expand-lg">
                            <a class="navbar-brand" href="#"><img src="assets/img/logo-multipurpose.png" alt="wrapkit" height="40" /></a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footer4" aria-expanded="false" aria-label="Toggle navigation">
                                <i class="fas fa-bars"></i>
                            </button>
                            <div class="collapse navbar-collapse" id="footer4">
                                <span class="d-none d-md-block d-lg-block">All Rights Reserved by O2System.</span>
                                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                                    <li class="nav-item active"><a class="nav-link" href="#">Home</a></li>
                                    <li class="nav-item"><a class="nav-link" href="#">About Me</a></li>
                                    <li class="nav-item"><a class="nav-link" href="#">Work</a></li>
                                    <li class="nav-item"><a class="nav-link" href="#">Services</a></li>
                                    <li class="nav-item"><a class="nav-link" href="#">Freebies</a></li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray pt-2 pb-0">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Footer 5</h1>
                <h6 class="subtitle">Below is footer. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <footer class="footer6 bg-dark">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4">
                    <div class="d-flex mb-2 text-white">
                        <div class="mr-3 "><i class="fas fa-phone"></i></div>
                        <div class="info">
                            <span class="d-block">(+62) 123 4567</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="d-flex mb-2">
                        <div class="mr-3 text-white"><i class="fas fa-envelope"></i></div>
                        <div class="info">
                            <a href="#" class="d-blockb text-white">info@infinite.com</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 ml-auto">
                    <div class="ml-auto round-social">
                        <a href="#" class=""><i class="fab fa-facebook"></i></a>
                        <a href="#" class=""><i class="fab fa-twitter"></i></a>
                        <a href="#" class=""><i class="fab fa-linkedin"></i></a>
                        <a href="#" class=""><i class="fab fa-pinterest"></i></a>
                        <a href="#" class=""><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
                <div class="col-md-12 copyright mt-3">
                    <div class="pt-3">Copyright 2018. All Rights Reserved by O2System.</div>
                </div>
            </div>
        </div>
    </footer>
</section>