<div class="static-slider static-slider-type-1" style="background-image:url(assets/img/multipurpose/bg-color.jpg)">
    <div class="container">
        <div class="row justify-content-center ">
            <div class="col-md-8 align-self-center text-center" data-aos="fade-right" data-aos-duration="1200">
                <h1 class="title text-light text-uppercase">Form Advanced</h1>
                <h5 class="text-light font-weight-normal">With Infinite Multipurpose, you can create everything, weather its Landing page, Complete Website, Lead generation or Coming soon etc.</h5>
            </div>
        </div>
    </div>
</div>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Form Advanced</h1>
                <h6 class="subtitle">Below is contact. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Select2</div>
                    <div class="card-body">
                        <h6 class="card-subtitle"> Select2 for custom search and select</h6>
                        <h5 class="mt-3">Single select2</h5>
                        <pre>
                            <code>
                                <select class="select2" style="width: 100%">
                                    <option>Select</option>
                                    <optgroup label="Alaskan/Hawaiian Time Zone">
                                        <option value="AK">Alaska</option>
                                        <option value="HI">Hawaii</option>
                                    </optgroup>
                                    <optgroup label="Pacific Time Zone">
                                        <option value="CA">California</option>
                                        <option value="NV">Nevada</option>
                                        <option value="OR">Oregon</option>
                                        <option value="WA">Washington</option>
                                    </optgroup>
                                </select>
                            </code>
                        </pre>
                        <select class="select2" style="width: 100%">
                            <option>Select</option>
                            <optgroup label="Alaskan/Hawaiian Time Zone">
                                <option value="AK">Alaska</option>
                                <option value="HI">Hawaii</option>
                            </optgroup>
                            <optgroup label="Pacific Time Zone">
                                <option value="CA">California</option>
                                <option value="NV">Nevada</option>
                                <option value="OR">Oregon</option>
                                <option value="WA">Washington</option>
                            </optgroup>
                        </select>
                        <h5 class="mt-3">Multiple select boxes</h5>
                        <select class="select2 mb-3 select2-multiple" style="width: 100%" multiple="multiple" data-placeholder="Choose">
                            <optgroup label="Alaskan/Hawaiian Time Zone">
                                <option value="AK">Alaska</option>
                                <option value="HI">Hawaii</option>
                            </optgroup>
                            <optgroup label="Pacific Time Zone">
                                <option value="CA">California</option>
                                <option value="NV">Nevada</option>
                                <option value="OR">Oregon</option>
                                <option value="WA">Washington</option>
                            </optgroup>
                        </select>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Switchery</div>
                    <div class="card-body">
                        <h5>Basic</h5>
                        <h6 class="card-subtitle"> add the following line <code>class="js-switch" data-color="#009efb"</code> to your input element. </h6>
                        <div class="switchery-demo mb-3">
                            <input type="checkbox" checked class="js-switch" data-color="#009efb" />
                            <input type="checkbox" checked class="js-switch" data-color="#f62d51" />
                            <input type="checkbox" checked class="js-switch" data-color="#55ce63" />
                            <input type="checkbox" checked class="js-switch" data-color="#ffbc34" />
                            <input type="checkbox" checked class="js-switch" data-color="#7460ee" />
                            <input type="checkbox" checked class="js-switch" data-color="#3d3b3b" />
                        </div>

                        <h5 class="mt-3">Size</h5>
                        <h6 class="card-subtitle"> You can add <code>data-size="small"</code>, <code>data-size="large"</code> to your input element for different sizes.  </h6>
                        <div class="mb-3">
                            <input type="checkbox" checked class="js-switch" data-color="#f62d51" data-size="small" />
                            <input type="checkbox" checked class="js-switch" data-color="#55ce63" />
                            <input type="checkbox" checked class="js-switch" data-color="#ffbc34" data-size="large" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Input Tags</div>
                    <div class="card-body">
                        <h6 class="card-subtitle">Add <code>data-role="tagsinput"</code> to your input field & its automatically change it to a tags input.</h6>
                        <div class="tags-default">
                            <input type="text" value="Amsterdam,Washington,Sydney" data-role='tagsinput' placeholder="add tags" />
                        </div>

                        <h6 class="card-subtitle mt-4">You can also use <code>select multiple</code> to your input field.</h6>
                        <select multiple data-role='tagsinput'>
                            <option value="Amsterdam">Amsterdam</option>
                            <option value="Washington">Washington</option>
                            <option value="Sydney">Sydney</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Spin</div>
                    <div class="card-body">
                         <h6 class="card-subtitle">Use the <code> data-plugin="touchSpin" </code> to create a Bootstrap style spinner.</h6>
                         <div class="row">
                            <div class="col-lg-6">
                                <form>
                                    <div class="form-group">
                                        <label class="control-label">Vertical Touchspin</label>
                                        <input class="vertical-spin" type="text" data-bts-button-down-class="btn btn-primary btn-outline" data-bts-button-up-class="btn btn-primary btn-outline" value="" name="vertical-spin">
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Postfix</label>
                                        <input id="tch1" type="text" value="55" name="tch1" data-bts-button-down-class="btn btn-primary btn-outline" data-bts-button-up-class="btn btn-primary btn-outline">
                                    </div>
                                    <div class="form-group mb-0">
                                        <label class="control-label">Prefix</label>
                                        <input id="tch2" type="text" value="0" name="tch2" class=" form-control" data-bts-button-down-class="btn btn-primary btn-outline" data-bts-button-up-class="btn btn-primary btn-outline">
                                    </div>
                                </form>
                            </div>
                            <div class="col-lg-6">
                                <form>
                                    <div class="form-group">
                                        <label class="control-label">Init </label>
                                        <input id="tch3" type="text" value="" name="tch3" data-bts-button-down-class="btn btn-primary btn-outline" data-bts-button-up-class="btn btn-primary btn-outline">
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Value set 30 </label>
                                        <input id="tch3_22" type="text" value="30" name="tch3_22" data-bts-button-down-class="btn btn-primary btn-outline" data-bts-button-up-class="btn btn-primary btn-outline">
                                    </div>
                                    <div class="form-group mb-0">
                                        <label class="control-label">Button group</label>
                                        <div class="input-group">
                                            <input id="tch5" type="text" class="form-control" name="tch5" value="50" data-bts-button-down-class="btn btn-primary btn-outline" data-bts-button-up-class="btn btn-primary btn-outline">
                                            <div class="input-group-append">
                                                <button type="button" class="btn btn-primary btn-outline dropdown-toggle" data-toggle="dropdown"> <span class="caret"></span> <span class="sr-only">Toggle Dropdown</span> </button>
                                                <div class="dropdown-menu"> 
                                                    <a class="dropdown-item" href="#">Action</a> 
                                                    <a class="dropdown-item" href="#">Another action</a> 
                                                    <a class="dropdown-item" href="#">Something else here</a>
                                                    <div class="dropdown-divider"></div> 
                                                    <a class="dropdown-item" href="#">Separated link</a> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Multiple Select</div>
                    <div class="card-body">
                        <h6 class="card-subtitle"> Use a <code>select multiple</code> as your input element.</h6>
                        <div class="row">
                            <div class="col-lg-6 mb-5">
                                <h5 class="box-title">Pre-selected options</h5>
                                <select id='pre-selected-options' multiple='multiple'>
                                    <option value='elem_1'>elem 1</option>
                                    <option value='elem_2'>elem 2</option>
                                    <option value='elem_3'>elem 3</option>
                                    <option value='elem_4' selected>elem 4</option>
                                    <option value='elem_5' selected>elem 5</option>
                                    <option value="elem_6">elem 6</option>
                                    <option value="elem_7">elem 7</option>
                                    <option value="elem_8">elem 8</option>
                                    <option value="elem_9">elem 9</option>
                                    <option value="elem_10">elem 10</option>
                                    <option value="elem_11">elem 11</option>
                                    <option value="elem_12">elem 12</option>
                                    <option value="elem_13">elem 13</option>
                                    <option value="elem_14">elem 14</option>
                                    <option value="elem_15">elem 15</option>
                                    <option value="elem_16">elem 16</option>
                                    <option value="elem_17">elem 17</option>
                                    <option value="elem_18">elem 18</option>
                                    <option value="elem_19">elem 19</option>
                                    <option value="elem_20">elem 20</option>
                                </select>
                            </div>
                            <div class="col-lg-6">
                                <h5 class="box-title">Optgroup</h5>
                                <select multiple id="optgroup" name="optgroup[]">
                                    <optgroup label="Friends">
                                        <option value="1">Yoda</option>
                                        <option value="2" selected disabled>Obiwan</option>
                                    </optgroup>
                                    <optgroup label="Enemies">
                                        <option value="3">Palpatine</option>
                                        <option value="4" disabled>Darth Vader</option>
                                    </optgroup>
                                </select>
                            </div>
                            <div class="col-lg-12">
                                <h5 class="box-title">Public methods</h5>
                                <select multiple id="public-methods" name="public-methods[]">
                                    <option value="elem_1">elem 1</option>
                                    <option value="elem_2" disabled>elem 2</option>
                                    <option value="elem_3">elem 3</option>
                                    <option value="elem_4">elem 4</option>
                                    <option value="elem_5">elem 5</option>
                                    <option value="elem_6">elem 6</option>
                                    <option value="elem_7">elem 7</option>
                                    <option value="elem_8">elem 8</option>
                                </select>
                                <div class="button-box mt-3">
                                    <a id="select-all" class="btn btn-danger" href="#">select all</a>
                                    <a id="deselect-all" class="btn btn-info" href="#">deselect all</a>
                                    <a id="add-option" class="btn btn-success" href="#">Add option</a>
                                    <a id="refresh" class="btn btn-warning" href="#">refresh</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Checkbox & Radio Button</div>
                    <div class="card-body">
                        <h6 class="card-subtitle">
                            Use a <code><div class="checkbox"> <input id="checkbox0" type="checkbox"><label for="checkbox0"> Default </label></div></code> as your input element.
                        </h6>
                        <div class="row">
                            <div class="col-xlg-2 col-lg-4 col-md-6 col-xs-12">
                                <h4 class="card-title mt-5">Checkbox Square</h4>
                                <h6 class="card-subtitle mb-4"> Bootstrap brand colors </h6>
                                <div class="checkbox">
                                    <input id="checkbox0" type="checkbox">
                                    <label for="checkbox0"> Default </label>
                                </div>
                                <div class="checkbox checkbox-custom">
                                    <input id="checkbox11" type="checkbox" checked>
                                    <label for="checkbox11"> Custom </label>
                                </div>
                                <div class="checkbox checkbox-primary">
                                    <input id="checkbox2" type="checkbox" checked>
                                    <label for="checkbox2"> Primary </label>
                                </div>
                                <div class="checkbox checkbox-success">
                                    <input id="checkbox3" type="checkbox">
                                    <label for="checkbox3"> Success </label>
                                </div>
                                <div class="checkbox checkbox-info">
                                    <input id="checkbox4" type="checkbox">
                                    <label for="checkbox4"> Info </label>
                                </div>
                                <div class="checkbox checkbox-warning">
                                    <input id="checkbox5" type="checkbox" checked>
                                    <label for="checkbox5"> Warning </label>
                                </div>
                                <div class="checkbox checkbox-danger">
                                    <input id="checkbox6" type="checkbox" checked>
                                    <label for="checkbox6"> Danger </label>
                                </div>
                                <div class="checkbox checkbox-purple">
                                    <input id="checkbox6a" type="checkbox">
                                    <label for="checkbox6a"> Purple </label>
                                </div>
                                <div class="checkbox checkbox-inverse">
                                    <input id="checkbox6c" type="checkbox">
                                    <label for="checkbox6c"> Inverse </label>
                                </div>
                            </div>
                            <div class="col-xlg-2 col-lg-4 col-md-6 col-xs-12">
                                <h4 class="card-title mt-5">Checkbox Circle</h4>
                                <h6 class="card-subtitle mb-4">Add simple <code>checkbox-circle</code> class </h6>
                                <div class="checkbox checkbox-circle">
                                    <input id="checkbox7" type="checkbox">
                                    <label for="checkbox7"> Simply Rounded </label>
                                </div>
                                <div class="checkbox checkbox-info checkbox-circle">
                                    <input id="checkbox8" type="checkbox" checked>
                                    <label for="checkbox8"> Info </label>
                                </div>
                                <div class="checkbox checkbox-primary checkbox-circle">
                                    <input id="checkbox-9" type="checkbox">
                                    <label for="checkbox-9"> Primary </label>
                                </div>
                                <div class="checkbox checkbox-success checkbox-circle">
                                    <input id="checkbox-10" type="checkbox" checked>
                                    <label for="checkbox-10"> Success </label>
                                </div>
                                <div class="checkbox checkbox-warning checkbox-circle">
                                    <input id="checkbox-11" type="checkbox">
                                    <label for="checkbox-11"> Warning </label>
                                </div>
                                <div class="checkbox checkbox-danger checkbox-circle">
                                    <input id="checkbox-12" type="checkbox" checked>
                                    <label for="checkbox-12"> Danger </label>
                                </div>
                                <div class="checkbox checkbox-purple checkbox-circle">
                                    <input id="checkbox-13" type="checkbox" checked>
                                    <label for="checkbox-13"> Purple </label>
                                </div>
                                <div class="checkbox checkbox-inverse checkbox-circle">
                                    <input id="checkbox-15" type="checkbox" checked>
                                    <label for="checkbox-15"> Inverse </label>
                                </div>
                            </div>
                            <div class="col-xlg-2 col-lg-4 col-md-6 col-xs-12">
                                <h4 class="card-title mt-5">Checkbox Disable</h4>
                                <h6 class="card-subtitle mb-4"> Disable state </h6>
                                <div class="checkbox">
                                    <input id="checkbox9" type="checkbox" disabled>
                                    <label for="checkbox9"> Can't check this </label>
                                </div>
                                <div class="checkbox checkbox-warning checkbox-circle">
                                    <input id="checkbox110" type="checkbox" disabled checked>
                                    <label for="checkbox110"> And this </label>
                                </div>
                                <div class="checkbox checkbox-info">
                                    <input id="checkbox12" type="checkbox" disabled checked>
                                    <label for="checkbox12"> Can't check this </label>
                                </div>
                                <div class="checkbox checkbox-purple checkbox-circle">
                                    <input id="checkbox14" type="checkbox" disabled checked>
                                    <label for="checkbox14"> And this </label>
                                </div>
                            </div>
                            <div class="col-xlg-2 col-lg-4 col-md-6 col-xs-12">
                                <h4 class="card-title mt-5">Radio Buttons</h4>
                                <h6 class="card-subtitle mb-4"> With bootstrap colors </h6>
                                <div class="radio">
                                    <input type="radio" name="radio" id="radio1" value="option1" checked>
                                    <label for="radio1"> Default </label>
                                </div>
                                <div class="radio radio-custom">
                                    <input type="radio" name="radio" id="radio2" value="option2">
                                    <label for="radio2"> Custom </label>
                                </div>
                                <div class="radio radio-primary">
                                    <input type="radio" name="radio" id="radio3" value="option3">
                                    <label for="radio3"> Primary </label>
                                </div>
                                <div class="radio radio-success">
                                    <input type="radio" name="radio" id="radio4" value="option4">
                                    <label for="radio4"> Success </label>
                                </div>
                                <div class="radio radio-info">
                                    <input type="radio" name="radio" id="radio5" value="option5">
                                    <label for="radio5"> Info </label>
                                </div>
                                <div class="radio radio-danger">
                                    <input type="radio" name="radio" id="radio6" value="option6">
                                    <label for="radio6"> Danger </label>
                                </div>
                                <div class="radio radio-warning">
                                    <input type="radio" name="radio" id="radio7" value="option7">
                                    <label for="radio7"> Warning </label>
                                </div>
                                <div class="radio radio-purple">
                                    <input type="radio" name="radio" id="radio8" value="option8">
                                    <label for="radio8"> Purple </label>
                                </div>
                            </div>
                            <div class="col-xlg-2 col-lg-4 col-md-6 col-xs-12">
                                <h4 class="card-title mt-5">Radio Clickable</h4>
                                <h6 class="card-subtitle mb-4"> All buttons clickable </h6>
                                <div class="radio">
                                    <input type="radio" name="radio1" id="radio11" value="option1" checked>
                                    <label for="radio11"> Default </label>
                                </div>
                                <div class="radio radio-custom">
                                    <input type="radio" name="radio2" id="radio12" value="option2">
                                    <label for="radio12"> Custom </label>
                                </div>
                                <div class="radio radio-primary">
                                    <input type="radio" name="radio3" id="radio13" value="option3">
                                    <label for="radio13"> Primary </label>
                                </div>
                                <div class="radio radio-success">
                                    <input type="radio" name="radio4" id="radio14" value="option4" checked>
                                    <label for="radio14"> Success </label>
                                </div>
                                <div class="radio radio-info">
                                    <input type="radio" name="radio5" id="radio15" value="option5" checked>
                                    <label for="radio15"> Info </label>
                                </div>
                                <div class="radio radio-danger">
                                    <input type="radio" name="radio6" id="radio16" value="option6">
                                    <label for="radio16"> Danger </label>
                                </div>
                                <div class="radio radio-warning">
                                    <input type="radio" name="radio7" id="radio17" value="option7" checked>
                                    <label for="radio17"> Warning </label>
                                </div>
                                <div class="radio radio-purple">
                                    <input type="radio" name="radio8" id="radio18" value="option8">
                                    <label for="radio18"> Purple </label>
                                </div>
                            </div>
                            <div class="col-xlg-2 col-lg-4 col-md-6 col-xs-12">
                                <h4 class="card-title mt-5">Radio Disable</h4>
                                <h6 class="card-subtitle mb-4"> Disable state </h6>
                                <div class="radio">
                                    <input type="radio" name="radio21" id="radio21" value="option1" disabled checked>
                                    <label for="radio21"> Default </label>
                                </div>
                                <div class="radio radio-custom">
                                    <input type="radio" name="radio22" disabled id="radio22" value="option2">
                                    <label for="radio22"> Custom </label>
                                </div>
                                <div class="radio radio-primary">
                                    <input type="radio" name="radio23" disabled id="radio23" value="option3">
                                    <label for="radio23"> Primary </label>
                                </div>
                                <div class="radio radio-success">
                                    <input type="radio" name="radio24" disabled id="radio24" value="option4" checked>
                                    <label for="radio24"> Success </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Clock Picker</div>
                    <div class="card-body">
                        <h6 class="card-subtitle">Use <code>.clockpicker</code> to create it.</h6>
                        <div class="row">
                            <div class="col-md-6">
                                <label class="mt-3">Default Clock Picker</label>
                                <div class="input-group clockpicker">
                                    <input type="text" class="form-control" value="09:30">
                                    <div class="input-group-append"> 
                                        <span class="input-group-text">
                                            <i class="fas fa-clock"></i>
                                        </span>
                                    </div>
                                </div>
                                <label class="mt-5">Auto close Clock Picker</label>
                                <div class="input-group clockpicker " data-placement="bottom" data-align="top" data-autoclose="true">
                                    <input type="text" class="form-control" value="13:14"> 
                                    <div class="input-group-append">
                                        <span class="input-group-text">
                                            <i class="fas fa-clock"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label class="mt-3">Now time</label>
                                <div class="input-group">
                                    <input class="form-control" id="single-input" value="" placeholder="Now"> 
                                    <div class="input-group-append">
                                        <button type="button" id="check-minutes" class="btn waves-effect waves-light btn-success">Check the minutes</button>
                                    </div> 
                                </div>
                                <label class="mt-5">Left Placement</label>
                                <div class="input-group clockpicker " data-placement="left" data-align="top" data-autoclose="true">
                                    <input type="text" class="form-control" value="13:14"> 
                                    <div class="input-group-append">
                                        <span class="input-group-text">
                                            <i class="fas fa-clock"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Color Picker</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4 mb-3">
                                <div class="example">
                                    <h5 class="box-title">Simple mode</h5>
                                    <p class="text-muted mb-3">just add class <code>.colorpicker</code> to create it.</p>
                                    <input type="text" class="colorpicker form-control" value="#7ab2fa" />
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <div class="example">
                                    <h5 class="box-title">Complex mode</h5>
                                    <p class="text-muted mb-3">just add class <code>.complex-colorpicker</code> to create it.</p>
                                    <input type="text" class="complex-colorpicker form-control" value="#fa7a7a" />
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <div class="example">
                                    <h5 class="box-title">Gradiant mode</h5>
                                    <p class="text-muted mb-3">just add class <code>.gradient-colorpicker-colorpicker</code> to create it.</p>
                                    <input type="text" class="gradient-colorpicker form-control" value="#bee0ab" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Daterange Picker</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="example">
                                    <h5 class="box-title mt-3">Date Range Pick</h5>
                                    <input class="form-control input-daterange-datepicker" type="text" name="daterange" value="01/01/2015 - 01/31/2015" />
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="example">
                                    <h5 class="box-title mt-3">Date Range With Time</h5>
                                    <input type="text" class="form-control input-daterange-timepicker" name="daterange" value="01/01/2015 1:30 PM - 01/01/2015 2:00 PM" />
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="example">
                                    <h5 class="box-title mt-3">Limit Selectable Dates</h5>
                                    <input class="form-control input-limit-datepicker" type="text" name="daterange" value="06/01/2015 - 06/07/2015" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Default Datepicker</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="example">
                                    <h5 class="box-title mt-3">Default Datedpicker</h5>
                                    <p class="text-muted mb-3">just add class <code>.mydatepicker</code> to create it.</p>
                                    <div class="input-group">
                                        <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="fa fa-calendar"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="example">
                                    <h5 class="box-title mt-3">Autoclose Datedpicker</h5>
                                    <p class="text-muted mb-3">just add class <code></code> to create it.</p>
                                    <div class="input-group">
                                        <input type="text" class="form-control" id="datepicker-autoclose" placeholder="mm/dd/yyyy">
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="fa fa-calendar"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="example">
                                    <h5 class="box-title mt-3">Date Range picker</h5>
                                    <p class="text-muted mb-3">just add id <code>#date-range</code> to create it.</p>
                                    <div class="input-daterange input-group" id="date-range">
                                        <input type="text" class="form-control" name="start" />
                                        <div class="input-group-append input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fa fa-calendar"></i>
                                            </span>
                                        </div>
                                        <input type="text" class="form-control" name="end" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="text-center">
                                    <h5 class="box-title mt-3">Datepicker Inline</h5>
                                    <p class="text-muted mb-3">You also can set the datepicker to be inline and flat.</p>
                                    <center>
                                        <div id="datepicker-inline"></div>
                                    </center>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Form Mask</div>
                    <div class="card-body">
                        <h6 class="card-subtitle">Use the button classes on an <code>data-mask</code> to the input element.</h6>
                        <form action="#">
                            <div class="form-group">
                                <label>Phone</label>
                                <input type="text" placeholder="" data-mask="(999) 999-9999" class="form-control">
                                <span class="form-text text-muted">(999) 999-9999</span>
                            </div>
                            <div class="form-group">
                                <label>Date</label>
                                <input type="text" placeholder="" data-mask="99/99/9999" class="form-control">
                                <span class="form-text text-muted">dd/mm/yyyy</span>
                            </div>
                            <div class="form-group">
                                <label>SSN field 1</label>
                                <input type="text" placeholder="" data-mask="999-99-9999" class="form-control">
                                <span class="form-text text-muted">e.g "999-99-9999"</span>
                            </div>
                            <div class="form-group">
                                <label>Phone field + ext.</label>
                                <input type="text" placeholder="" data-mask="+40 999 999 999" class="form-control">
                                <span class="form-text text-muted">+40 999 999 999</span>
                            </div>
                            <div class="form-group">
                                <label>Product Key</label>
                                <input type="text" placeholder="" data-mask="a*-999-a999" class="form-control">
                                <span class="form-text text-muted">e.g a*-999-a999</span>
                            </div>
                        </form>
                        <form action="#">
                            <div class="form-group">
                                <label>Currency</label>
                                <input type="text" placeholder="" data-mask="$ 999,999,999.99" class="form-control">
                                <span class="form-text text-muted">$ 999,999,999.99</span>
                            </div>
                            <div class="form-group">
                                <label>Date 2</label>
                                <input type="text" placeholder="" data-mask="99-99-9999" class="form-control">
                                <span class="form-text text-muted">dd-mm-yyyy</span>
                            </div>
                            <div class="form-group">
                                <label>Eye Script</label>
                                <input type="text" placeholder="" data-mask="~9.99 ~9.99 999" class="form-control">
                                <span class="form-text text-muted">~9.99 ~9.99 999</span>
                            </div>
                            <div class="form-group">
                                <label>Percent</label>
                                <input type="text" placeholder="" data-mask="99%" class="form-control">
                                <span class="form-text text-muted">e.g "99%"</span>
                            </div>
                            <div class="form-group m-b-0">
                                <label>Pc Ip</label>
                                <input type="text" placeholder="" data-mask="999.999.999.9999" class="form-control">
                                <span class="form-text text-muted">e.g "999.999.999.9999"</span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Dropzone</div>
                    <div class="card-body">
                        <form class="form-horizontal" action="data/upload-file.php">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="dropzone" id="dropzone-wrap">
                                        <div class="fallback">
                                            <input name="file" type="file" multiple />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 mt-3 hidden" id="dze_info">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th width="40%">File name</th>
                                                <th width="15%">Size</th>
                                                <th width="15%">Type</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <td colspan="4"></td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">TinyMCE</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 mb-5">
                                <h5>TinyMCE Full</h5>
                                <h6 class="card-subtitle"> add the following line <code>class="tinymce-full"</code> to your input element. </h6>
                                <textarea class="form-control tinymce-full"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 mb-5">
                                <h5>TinyMCE Minimal</h5>
                                <h6 class="card-subtitle"> add the following line <code>class="tinymce-minimal"</code> to your input element. </h6>
                                <textarea class="form-control tinymce-minimal"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>