<div class="jumbotron rounded-0 vertical-center bg-dark text-white">
    <div class="container">
        <img src="./assets/img/logo/logo-200px.png" style="margin: 50px 0px; width: 200px !important; height: 200px !important;">
        <h1 class="display-4"><?php echo $page->header; ?></h1>
        <p class="lead text-uppercase">
            <?php echo $page->lead; ?>
        </p>
        <hr class="border-light">
        <p>
            <?php echo $page->author; ?>
        </p>
    </div>
</div>
<div class="container" style="padding: 10px 0px 50px 0px;">
    <h2 class="display-6">Unit Testing Report</h2>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Engine</th>
                <th>Result</th>
                <th>Expected</th>
                <th>Status</th>
                <th>Trace</th>
                <th>Notes</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach( $reports as $report ): ?>
                <tr class="<?php echo ( $report->status === 'passed' ? 'success' : 'danger' ); ?>">
                    <td width="20">
                        <strong><?php echo $report->label; ?></strong>
                    </td>
                    <td width="5">
                        <span class="badge badge-info"><?php echo $report->datatype->result; ?></span>
                    </td>
                    <td width="5">
                        <span class="badge badge-info"><?php echo $report->datatype->expected; ?></span>
                    </td>
                    <td width="5">
                        <?php if( $report->status === 'passed' ): ?>
                            <span class="badge badge-success">Passed</span>
                        <?php else: ?>
                            <span class="badge badge-danger">Failed</span>
                        <?php endif; ?>
                    </td>
                    <td width="10">
                        <i class="text-muted"><?php echo $report->trace->file; ?>:<?php echo $report->trace->line; ?></i>
                    </td>
                    <td width="20">
                        <p><?php echo $report->notes; ?></p>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>