<!DOCTYPE html>
<html>
<head>
    <title>{{$meta->title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css">

    {{$assets->head}}
</head>
<body class="admin-ui fix-header fix-sidebar">
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <header class="header">
        {{$partials->headeradd}}
    </header>

    <div class="sidebar">
        {{$partials->sidebar}}
    </div>

    <main class="main bg-white">
        <div class="container-fluid">
            {{$partials->content}}
        </div>

        <footer class="footer">
            {{$app->copyright}}
        </footer>
    </main>
{{$assets->body}}
</body>
</html>