<!DOCTYPE html>
<html>
<head>
    <title>{{$meta->title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css">

    {{$assets->head}}
</head>
<body class="admin-ui fix-header fix-sidebar">

    <header class="header">
        {{$partials->header}}
    </header>

    <div class="sidebar">
        {{$partials->sidebar}}
    </div>

    <main class="main">
        <div class="container-fluid">
            {{$partials->content}}
        </div>
    </main>
{{$assets->body}}
</body>
</html>