<section>
	<div class="container">
		<div class="row justify-content-center">
		    <div class="col-md-12">
		        <form method="post" action="">
		            <div class="card mb-3">
		                <div class="card-header">
		                    <div class="row align-items-center">
		                        <div class="col-md-10">
		                            <h6 class="mb-0">
		                                <button class="btn btn-default btn-xs">
		                                    <strong>DPS-BJN</strong>
		                                </button>
		                                <a href="javascript:void">
		                                    Denpasar (Mengwi) —
		                                    Bojonegoro (Rajekwesi)
		                                    <small> </small>
		                                </a>
		                            </h6>
		                            <hr class="mt-2 mb-2">
		                            <div class="btn btn-group btn-group-xs m-0 p-0">
		                                <button class="btn btn-danger btn-xs">IDR 225K</button>
		                                <button class="btn btn-default btn-xs">Executive</button>
		                            </div>
		                            <div class="btn btn-group btn-group-xs m-0 p-0">
		                                <button class="btn btn-warning btn-xs">Available</button>
		                                <button class="btn btn-default btn-xs">28 / 28</button>
		                            </div>


		                            <button class="btn btn-warning btn-xs btn-icon">
		                                <i class="fa fa-clock-o"></i> 1 hours and 40 minutes
		                            </button>
		                        </div>
		                        <div class="col-md-2">
		                            <select class="form-control custom-select">
		                                <option value="14">14:00 WITA</option>
		                            </select>
		                        </div>
		                    </div>
		                </div>
		                <div class="card-body">
		                    <div class="row">
		                        <div class="col-md-12">
		                            <ul class="progress-indicator">
		                                <li class="active">
		                                    Denpasar <span class="bubble"></span>
		                                    <small>Mengwi</small>
		                                </li>
		                                <li class="active">
		                                    Denpasar <span class="bubble"></span>
		                                    <small>Ubung</small>
		                                </li>
		                                <li class="active">
		                                    Tabanan <span class="bubble"></span>
		                                    <small>Pesiapan</small>
		                                </li>
		                                <li class="active">
		                                    Negara <span class="bubble"></span>
		                                    <small>Negara</small>
		                                </li>
		                                <li class="active">
		                                    Gilimanuk <span class="bubble"></span>
		                                    <small>Gilimanuk</small>
		                                </li>
		                                <li class="active">
		                                    Banyuwangi <span class="bubble"></span>
		                                    <small>Ketapang</small>
		                                </li>
		                                <li class="active">
		                                    Asembagus <span class="bubble"></span>
		                                    <small>Asembagus</small>
		                                </li>
		                                <li class="active">
		                                    Situbondo <span class="bubble"></span>
		                                    <small>Situbondo</small>
		                                </li>
		                                <li class="active">
		                                    Pasir Putih <span class="bubble"></span>
		                                    <small>Pasir Putih</small>
		                                </li>
		                                <li class="active">
		                                    Besuki <span class="bubble"></span>
		                                    <small>Besuki</small>
		                                </li>
		                                <li class="active">
		                                    Gresik <span class="bubble"></span>
		                                    <small>Bunder</small>
		                                </li>
		                                <li class="active">
		                                    Lamongan <span class="bubble"></span>
		                                    <small>Lamongan</small>
		                                </li>
		                                <li class="active">
		                                    Babat <span class="bubble"></span>
		                                    <small>Babat</small>
		                                </li>
		                                <li class="active">
		                                    Bojonegoro <span class="bubble"></span>
		                                    <small>Rajekwesi</small>
		                                </li>
		                            </ul>
		                        </div>
		                    </div>
		                </div>
		                <div class="card-footer">
		                    <div class="row align-items-center">
		                        <div class="col-md-5">
		                            <a href="javascript:void" class="btn btn-block btn-dark btn-lg">
		                                <h3>
		                                    <strong>DK 7376 AW</strong>
		                                </h3>
		                                <hr class="mt-1 mb-1 border-light">
		                                <small style="font-size: small;">Golden Dragon — YUNCHAI — SINGLE</small>
		                            </a>
		                        </div>
		                        <div class="col-md-7">
		                            <div class="row mt-sm-2 mt-2 mt-md-0">
		                                <div class="col">
		                                    <strong>Departure</strong>
		                                    <div class="float-right">
		                                        <h6 class="mb-0">
		                                            <strong>14:00</strong>
		                                            <small style="font-size: x-small;">WITA</small>
		                                        </h6>
		                                    </div>
		                                    <hr class="mt-1 mb-2">
		                                    <div class="form-group">
		                                        <select class="form-control custom-select select2">
		                                            <option value="58" selected="">Denpasar — Mengwi</option>
		                                            <option value="59">Denpasar — Ubung</option>
		                                            <option value="61">Tabanan — Pesiapan</option>
		                                            <option value="62">Negara — Negara</option>
		                                            <option value="63">Gilimanuk — Gilimanuk</option>
		                                            <option value="57">Banyuwangi — Ketapang</option>
		                                            <option value="70">Asembagus — Asembagus</option>
		                                            <option value="53">Situbondo — Situbondo</option>
		                                            <option value="71">Pasir Putih — Pasir Putih</option>
		                                            <option value="72">Besuki — Besuki</option>
		                                            <option value="40">Gresik — Bunder</option>
		                                            <option value="39">Lamongan — Lamongan</option>
		                                            <option value="69">Babat — Babat</option>
		                                            <option value="37">Bojonegoro — Rajekwesi</option>
			                                    </select>
		                                    </div>

		                                    <div class="form-group select2-sm">
		                                        <label>Pickup Point</label>
		                                        <select class="form-control form-control-sm select2">
		                                            <option value="0">Terminal Mengwi</option>
		                                        </select>
		                                    </div>
		                                </div>
		                                <div class="col">
		                                    <strong>Arrival</strong>
		                                    <div class="float-right">
		                                        <h6 class="mb-0">
		                                            <strong>14:00</strong>
		                                            <small style="font-size: x-small;">WITA</small>
		                                        </h6>
		                                    </div>
		                                    <hr class="mt-1 mb-2">
		                                    <div class="form-group">
		                                        <select class="form-control custom-select select2">
		                                            <option value="58">Denpasar — Mengwi</option>
		                                            <option value="59">Denpasar — Ubung</option>
		                                            <option value="61">Tabanan — Pesiapan</option>
		                                            <option value="62">Negara — Negara</option>
		                                            <option value="63">Gilimanuk — Gilimanuk</option>
		                                            <option value="57">Banyuwangi — Ketapang</option>
		                                            <option value="70">Asembagus — Asembagus</option>
		                                            <option value="53">Situbondo — Situbondo</option>
		                                            <option value="71">Pasir Putih — Pasir Putih</option>
		                                            <option value="72">Besuki — Besuki</option>
		                                            <option value="40">Gresik — Bunder</option>
		                                            <option value="39">Lamongan — Lamongan</option>
		                                            <option value="69">Babat — Babat</option>
		                                            <option value="37" selected="">Bojonegoro — Rajekwesi</option>
		                                        </select>
		                                    </div>

		                                    <div class="form-group select2-sm">
		                                        <label>Dropoff Point</label>
		                                        <select class="form-control form-control-sm select2">
		                                            <option value="0">Terminal Mengwi</option>
		                                        </select>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
		                    </div>
		                </div>
		            </div>

		            <div class="card mb-3">
		                <h6 class="card-header">
		                    Passenger Data
		                    <div class="card-options">
		                        <span class="badge badge-primary">1</span>
		                    </div>
		                </h6>
		                <div class="card-body">
		                    <div class="row">
		                        <div class="col-md-2">
		                            <div class="form-group">
		                                <label>Pilih Seat</label>
		                                <div class="bus seat2-2 border-0 p-0">
		                                    <div class="seat-row-1">
		                                        <ol class="seats">
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-1" value="1" type="radio">
		                                                <label for="seat-radio-1">1</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-2" value="2" type="radio">
		                                                <label for="seat-radio-2">2</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-3" value="3" type="radio">
		                                                <label for="seat-radio-3">3</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-4" value="4" type="radio">
		                                                <label for="seat-radio-4">4</label>
		                                            </li>
		                                        </ol>
		                                    </div>
		                                    <div class="seat-row-2">
		                                        <ol class="seats">
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-5" value="5" type="radio">
		                                                <label for="seat-radio-5">5</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-6" value="6" type="radio">
		                                                <label for="seat-radio-6">6</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-7" value="7" type="radio">
		                                                <label for="seat-radio-7">7</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-8" value="8" type="radio">
		                                                <label for="seat-radio-8">8</label>
		                                            </li>
		                                        </ol>
		                                    </div>
		                                    <div class="seat-row-3">
		                                        <ol class="seats">
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-9" value="9" type="radio">
		                                                <label for="seat-radio-9">9</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-10" value="10" type="radio">
		                                                <label for="seat-radio-10">10</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-11" value="11" type="radio">
		                                                <label for="seat-radio-11">11</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-12" value="12" type="radio">
		                                                <label for="seat-radio-12">12</label>
		                                            </li>
		                                        </ol>
		                                    </div>
		                                    <div class="seat-row-4">
		                                        <ol class="seats">
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-13" value="13" type="radio">
		                                                <label for="seat-radio-13">13</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-14" value="14" type="radio">
		                                                <label for="seat-radio-14">14</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-15" value="15" type="radio">
		                                                <label for="seat-radio-15">15</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-16" value="16" type="radio">
		                                                <label for="seat-radio-16">16</label>
		                                            </li>
		                                        </ol>
		                                    </div>
		                                    <div class="seat-row-5">
		                                        <ol class="seats">
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-17" value="17" type="radio">
		                                                <label for="seat-radio-17">17</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-18" value="18" type="radio">
		                                                <label for="seat-radio-18">18</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-19" value="19" type="radio">
		                                                <label for="seat-radio-19">19</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-20" value="20" type="radio">
		                                                <label for="seat-radio-20">20</label>
		                                            </li>
		                                        </ol>
		                                    </div>
		                                    <div class="seat-row-6">
		                                        <ol class="seats">
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-21" value="21" type="radio">
		                                                <label for="seat-radio-21">21</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-22" value="22" type="radio">
		                                                <label for="seat-radio-22">22</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-23" value="23" type="radio">
		                                                <label for="seat-radio-23">23</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-24" value="24" type="radio">
		                                                <label for="seat-radio-24">24</label>
		                                            </li>
		                                        </ol>
		                                    </div>
		                                    <div class="seat-row-7">
		                                        <ol class="seats">
		                                            <li class="seat">
		                                                <label for="seat-radio-BLANK" style="background: none;"></label>
		                                            </li>
		                                            <li class="seat">
		                                                <label for="seat-radio-BLANK" style="background: none;"></label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-25" value="25" type="radio">
		                                                <label for="seat-radio-25">25</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-26" value="26" type="radio">
		                                                <label for="seat-radio-26">26</label>
		                                            </li>
		                                        </ol>
		                                    </div>
		                                    <div class="seat-row-8">
		                                        <ol class="seats">
		                                            <li class="seat">
		                                                <label for="seat-radio-BLANK" style="background: none;"></label>
		                                            </li>
		                                            <li class="seat">
		                                                <label for="seat-radio-BLANK" style="background: none;"></label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-27" value="27" type="radio">
		                                                <label for="seat-radio-27">27</label>
		                                            </li>
		                                            <li class="seat">
		                                                <input name="seats[]" id="seat-radio-28" value="28" type="radio">
		                                                <label for="seat-radio-28">28</label>
		                                            </li>
		                                        </ol>
		                                    </div>
		                                </div>
		                                <div class="text-center mt-2">
		                                    <button class="btn btn-primary btn-xs mb-2">Tersedia</button>
		                                    <button class="btn btn-success btn-xs mb-2">Dipilih</button>
		                                    <button class="btn btn-danger btn-xs mb-2">Terisi</button>
		                                </div>
		                            </div>
		                        </div>
		                        <div class="col-md-10">
		                            <div class="form-row">
		                                <div class="form-group col-sm-4">
		                                    <label>Salutation</label>
		                                    <select name="salutation[]" class="form-control custom-select" required="">
		                                        <option value="MR" selected="">Tuan</option>
		                                        <option value="MRS">Nyonya</option>
		                                        <option value="MISS">Nona</option>
		                                        <option value="CHILD">Anak</option>
		                                    </select>
		                                </div>
		                                <div class="form-group col-sm-8">
		                                    <label>Full Name</label>
		                                    <input name="fullname[]" class="form-control" required="" type="text">
		                                </div>
		                            </div>
		                            <div class="form-row">
		                                <div class="form-group col-sm-4">
		                                    <label>Identity Type</label>
		                                    <select name="identity[type][]" class="form-control custom-select">
		                                        <option value="">KTP</option>
		                                        <option value="">SIM</option>
		                                        <option value="">Passport</option>
		                                    </select>
		                                </div>
		                                <div class="form-group col-sm-8">
		                                    <label>Identity Number</label>
		                                    <input name="identity[number][]" class="form-control" type="text">
		                                    <small class="form-text text-muted">
		                                        Bila tidak ada, mohon masukan tanggal lahir dalam format (DDMMYYY)
		                                    </small>
		                                </div>
		                            </div>
		                            <div class="form-row">
		                                <div class="form-group col-sm-6">
		                                    <label>Email</label>
		                                    <input name="email[]" class="form-control" type="text">
		                                    <small class="form-text text-muted">
		                                        E-Tiket Anda akan dikirim ke alamat email ini.
		                                    </small>
		                                </div>
		                                <div class="form-group col-sm-6">
		                                    <label>Mobile Phone</label>
		                                    <input name="msisdn[]" class="form-control" type="text">
		                                    <small class="form-text text-muted">
		                                        Bila tidak ada, mohon masukan tanggal lahir dalam format (DDMMYYY)
		                                    </small>
		                                </div>
		                            </div>
		                        </div>
		                    </div>
		                </div>
		            </div>
		            <div class="card mb-3">
		            	<div class="card-header">Metode Pembayaran</div>
		            	<div class="card-body">
		            		
		            	</div>
		            </div>
		            <div class="card mb-3">
		                <div class="card-body d-flex justify-content-between align-items-center">
		                    <div>
		                        <div class="btn btn-group btn-group-block m-0 p-0">
		                            <button type="button" class="btn btn-warning">
		                                <strong>Adults</strong>
		                            </button>
		                            <button type="button" class="btn btn-default">
		                                <strong>1</strong>
		                            </button>
		                        </div>

		                        <div class="btn btn-group btn-group-block ml-2 p-0">
		                            <button type="button" class="btn btn-info">
		                                <strong>Infants</strong>
		                            </button>
		                            <button type="button" class="btn btn-default">
		                                <strong>0</strong>
		                            </button>
		                        </div>
		                    </div>

		                    <div>
		                        <div class="btn btn-group btn-group-lg btn-group-block m-0 p-0">
		                            <button type="button" class="btn btn-default">
		                                <strong>IDR 229.500</strong>
		                            </button>
		                            <button type="submit" class="btn btn-primary">
		                                <strong>Checkout</strong>
		                            </button>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </form>
		    </div>
		</div>
	</div>
</section>