<section>
	<div class="container">
		<div class="row align-items-center">
			<div class="col-md-8">
				<div class="card mb-3">
				    <div class="card-header">
				        <div class="row align-items-center">
				            <div class="col-md-12 d-flex justify-content-between">
				                <h6 class="mb-0">
				                    <button class="btn btn-default btn-xs">
                                        <strong>DPS-BJN-201803031400WITA</strong>
                                    </button>
				                    <a href="javascript:void">
				                        Denpasar (Mengwi) — Bojonegoro (Rajekwesi)
				                    </a>
				                </h6>
				            </div>
				        </div>
				    </div>
				    <div class="card-body">
				        <div class="row align-items-center">
				            <div class="col-md-6">
				                <a href="" class="btn btn-block btn-dark btn-lg">
				                    <h3>
				                        <strong>DK 7376 AW</strong>
				                    </h3>
				                    <hr class="mt-1 mb-1 border-light">
				                    <small style="font-size: small;">
				                        Golden Dragon — YUNCHAI — SINGLE
				                    </small>
				                </a>
				            </div>
				            <div class="col-md-6">
				                <div class="row mt-sm-2 mt-2 mt-md-0">
				                    <div class="col">
				                        <strong>Departure</strong>
				                        <hr class="mt-1 mb-2">
				                        <h6 class="mb-0">
				                            <strong>14:00</strong>
				                            <small style="font-size: x-small;">WITA</small>
				                        </h6>
				                        <small>Denpasar - Mengwi</small>
				                    </div>
				                    <div class="col">
				                        <strong>Arrival</strong>
				                        <hr class="mt-1 mb-2">
				                        <h6 class="mb-0">
				                            <strong>14:00</strong>
				                            <small style="font-size: x-small;">WITA</small>
				                        </h6>
				                        <small>Bojonegoro - Rajekwesi</small>
				                    </div>
				                </div>
				            </div>
				        </div>
				    </div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card border-info mb-3">
				    <div class="card-body text-center">
				    	<p class="mb-3">
				    		Segera lakukan pembayaran untuk menghindari <strong>pembatalan otomatis</strong>.<br>Sisa waktu pembayaran:
				    	</p>
				    	<h4 class="mb-0 text-primary" data-countdown="2018/03/7"></h4>
				    </div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="card">
				    <div class="card-header">
                        Rincian Pemesanan
				    </div>
				    <div class="table-responsive">
					    <table class="table table-striped mb-0">
					        <tbody>
					            <tr>
					                <th>
					                    <div class="row align-items-center">
					                        <div class="col-md-9">
					                            Mr. Steeven Andrian <small>(KTP - 123412355235)</small>
					                            <hr class="m-0 p-0">
					                            <small><i class="fa fa-envelope"></i> steeven@gmail.com</small>
					                            <small><i class="fa fa-phone"></i> 081234567890</small>
					                        </div>

					                        <div class="col-md-3">
					                            <button type="button" class="btn btn-xs btn-warning">
					                                                    <strong>Adult</strong>
					                                                </button>

					                            <div class="btn btn-group btn-group-xs m-0 p-0">
					                                <button type="button" class="float-right btn btn-xs btn-info">
					                                                        <strong>Seat</strong>
					                                                    </button>
					                                <button type="button" class="float-right btn btn-xs btn-default">
					                                                        <strong>23</strong>
					                                                    </button>
					                            </div>
					                        </div>
					                    </div>
					                </th>
					                <td>IDR</td>
					                <td class="text-right">225.000</td>
					            </tr>
					        </tbody>
					        <tfoot>
					            <tr class="text-muted">
					                <th class="text-right">
					                    Subtotal
					                </th>
					                <th>IDR</th>
					                <th class="text-right">225.000</th>
					            </tr>
					            <tr class="text-muted">
					                <th class="text-right">
					                    Biaya Layanan
					                </th>
					                <th>IDR</th>
					                <th class="text-right">4.500</th>
					            </tr>
					            <tr class="text-success">
					                <th class="text-right">
					                    Total
					                </th>
					                <th>IDR</th>
					                <th class="text-right" data-role="total-amount" data-amount="229500">229.500</th>
					            </tr>
					            <tr class="text-info" data-role="payment-form" style="display: none;">
					                <th class="text-right">
					                    Payment
					                </th>
					                <th>IDR</th>
					                <th class="text-right">
					                    <div class="input-group">
					                        <input name="payment-amount" value="0" class="form-control" type="number">
					                        <div class="input-group-btn">
					                            <button type="submit" class="btn btn-primary">Submit</button>
					                        </div>
					                    </div>
					                </th>
					            </tr>
					            <tr class="text-warning" data-role="payment-form" style="display: none;">
					                <th class="text-right">
					                    Change
					                </th>
					                <th>IDR</th>
					                <th class="text-right" data-role="payment-form-change">
					                    0
					                </th>
					            </tr>
					        </tfoot>
					    </table>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>