<div class="container text-center">

    <ul class="list-inline text-uppercase">
        <li class="list-inline-item">
            <a href="http://o2system.id/about">About</a>
        </li>
        <li class="list-inline-item">
            <a href="http://o2system.id/features">Features</a>
        </li>
        <li class="list-inline-item">
            <a href="http://o2system.id/documentation">Documentation</a>
        </li>
        <li class="list-inline-item">
            <a href="http://o2system.id/screencast">Screencast</a>
        </li>
        <li class="list-inline-item">
        <a href="http://o2system.id/blog">Blog</a>
    </li>
    </ul>

    <p class="trademark-text">O2System UI is a Trademark of Teguh Rianto</p>
    <div class="trademark-logo">
        <img src="assets/img/teguh-rianto-autograf.png">
    </div>
</div>