<nav class="navbar navbar-expand-md navbar-light navbar-type-1 bg-white">
    <div class="container position-relative">
        <a class="navbar-brand" href="#">
            <img class="" src="assets/img/logo-multipurpose.png" alt="Infinite Multipurpose" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-header" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="main-header">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <li class="nav-item dropdown mega-dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Demos
                    </a>
                    <div class="dropdown-menu border-0 animated fadeInUp">
                        <div class="row">
                            <div class="col-lg-3 inside-bg d-md-block d-lg-block d-none">
                                <div class="bg-img" style="background-image:url(assets/img/bg-galaxy.jpg)">
                                    <h4 class="text-white font-weight-normal">Most Powerfull Bootstrap 4 UI Kit</h4>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-6">
                                <ul>
                                    <li><h6>Niche Homepages</h6></li>
                                    <li><a href="#">Business</a></li>
                                    <li><a href="#" target="_blank">Creative</a></li>
                                    <li><a href="#" target="_blank">Charity</a></li>
                                    <li><a href="#" target="_blank">Health & Medical</a></li>
                                    <li><a href="#" target="_blank">Software Application</a></li>
                                    <li><a href="#" target="_blank">Real Estate</a></li>
                                    <li><a href="#" target="_blank">Restaurant</a></li>
                                    
                                </ul>
                            </div>
                            <div class="col-lg-2 col-md-6">
                                <ul class="list-style-none">
                                    <li><h6>&nbsp;</h6></li>
                                    <li><a href="#" target="_blank">Web-Agency</a></li>
                                    <li><a href="#" target="_blank">Fitness</a></li>
                                    <li><a href="#" target="_blank">Accounting</a></li>
                                    <li><a href="#" target="_blank">One Page</a></li>
                                    <li><a href="#" target="_blank">Marketing / SEO</a></li>
                                    <li><a href="#" target="_blank">Industrial</a></li>
                                    <li><a href="#" target="_blank">Cryptocurrency</a></li>
                                    
                                </ul>
                            </div>
                            <div class="col-lg-2 col-md-6">
                                <ul class="list-style-none">
                                    <li><h6>Landing Pages</h6></li>
                                    <li><a href="#" target="_blank">App Landing</a></li>
                                    <li><a href="#" target="_blank">Health & Medical</a></li>
                                    <li><a href="#" target="_blank">Personal Landing</a></li>
                                    <li><a href="#" target="_blank">Form Landing</a></li>
                                    <li><a href="#" target="_blank">Appointment Landing</a></li>
                                    <li><a class="text-muted">More Coming soon...</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-3 col-md-6">
                                <ul class="list-style-none">
                                    <li><h6>Freelancer / Portfolio</h6></li>
                                    <li><a href="#" target="_blank">Freelancer 1</a></li>
                                    <li><a href="#" target="_blank">Freelancer 2</a></li>
                                    <li><a href="#" target="_blank">Photographer Light</a></li>
                                    <li><a href="#" target="_blank">Photographer Dark</a></li>
                                    <li><a href="#" target="_blank">Comming Soon</a></li>
                                </ul>
                            </div>
                            
                        </div>
                    </div>
                </li>
                <li class="nav-item dropdown mega-dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Sections
                    </a>
                    <div class="dropdown-menu border-0 animated fadeInUp">
                        <div class="row">
                            <div class="col-lg-4 inside-bg hidden-md-down">
                                <div class="bg-img" style="background-image:url(assets/img/bg-galaxy.jpg)">
                                    <h3 class="text-white font-weight-normal">Create anything <br/>with our amazing <br/>sections</h3>
                                </div>
                            </div>
                            
                            <div class="col-lg-2 col-md-4">
                                <ul class="list-style-none">
                                    <li><h6>Headers &amp; Footers</h6></li>
                                    <li><a href="#" target="_blank">Banners</a></li>
                                    <li><a href="#" target="_blank">Form Banners</a></li>
                                    <li><a href="{{base_url('multipurpose/navigation1')}}" target="_blank">Navigation 1-10</a></li>
                                    <li><a href="#" target="_blank">Navigation 11-20</a></li>
                                    <li><a href="#" target="_blank">Footers</a></li>
                                    <li><a href="#" target="_blank">Call to Actions</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-1 col-md-4">
                                <ul class="list-style-none">
                                    <li><h6>Sliders</h6></li>
                                    <li><a href="#" target="_blank">Slider1</a></li>
                                    <li><a href="#" target="_blank">Slider2</a></li>
                                    <li><a href="#" target="_blank">Slider3</a></li>
                                    <li><a href="#" target="_blank">Slider4</a></li>
                                    <li><a href="#" target="_blank">Slider5</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-1 col-md-4">
                                <ul class="list-style-none">
                                    <li><h6>&nbsp;</h6></li>
                                    <li><a href="#" target="_blank">Slider6</a></li>
                                    <li><a href="#" target="_blank">Slider7</a></li>
                                    <li><a href="#" target="_blank">Slider8</a></li>
                                    <li><a href="#" target="_blank">Slider9</a></li>
                                    <li><a href="#" target="_blank">Slider10</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-2 col-md-4">
                                <ul class="list-style-none">
                                    <li><h6>Other Sections</h6></li>
                                    <li><a href="#" target="_blank">Contacts</a></li>
                                    <li><a href="#" target="_blank">Blogs</a></li>
                                    <li><a href="#" target="_blank">Pricing</a></li>
                                    <li><a href="#" target="_blank">Teams</a></li>
                                    <li><a href="#" target="_blank">Testimonials</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-2 col-md-4">
                                <ul class="list-style-none">
                                    <li><h6>Features</h6></li>
                                    <li><a href="#" target="_blank">Features 1-10</a></li>
                                    <li><a href="#" target="_blank">Features 11-20</a></li>
                                    <li><a href="#" target="_blank">Features 21-30</a></li>
                                    <li><a href="#" target="_blank">Features 31-40</a></li>
                                    <li><a href="#" target="_blank">Features 41-50</a></li>
                                </ul>
                            </div>
                            
                        </div>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Pages
                    </a>
                    <ul class="border-0 dropdown-menu animated fadeInUp">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                        <li class="divider" role="separator"></li>
                        <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" data-toggle="dropdown" href="#">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                            <ul class="dropdown-menu border-0 menu-right">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                                <li class="divider" role="separator"></li>
                                <li><a class="dropdown-item" href="#">Separated link</a></li>
                                <li class="divider" role="separator"></li>
                                <li><a class="dropdown-item" href="#">One more separated link</a></li>
                            </ul>
                        </li>
                        <li><a class="dropdown-item" href="#">Separated link</a></li>
                        <li class="divider" role="separator"></li>
                        <li><a class="dropdown-item" href="#">One more separated link</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a class="btn btn-outline-success" href="#">Hire Me</a></li>
            </ul>
        </div>
    </div>
</nav>