<div class="banner">
    <div class="jumbotron jumbotron-bg text-center rounded-0" style="background-image: url('assets/img/bg-galaxy.jpg');">
        <div class="container">
            <h1 class="pt-5">
                {{$title}}
            </h1>
            <p class="lead">
                This is about page with {{$username}}
            </p>
        </div>
    </div>
</div>
<section id="main-role" class="section-basic">
    <div class="container">
        <h2 class="section-basic-heading">
            Main Role Team
        </h2>
        <div class="row mt-5 justify-content-center">
            <div class="col-md-5">
                <div class="card card-outline-default mb-5 text-center">
                    <img src="assets/img/about/steevenz.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">
                            Steeven Andrian Salim
                        </h5>
                        <p class="card-text">Founder</p>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="card card-outline-default mb-5 text-center">
                    <img src="assets/img/about/teguh.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">
                            Teguh Rianto
                        </h5>
                        <p class="card-text">UI Developer</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="support-team" class="section-basic gray-bg">
    <div class="container">
        <h2 class="section-basic-heading">
            Support Team
        </h2>
        <div class="row mt-5 justify-content-center">
            <div class="col-md-4">
                <div class="card card-outline-default mb-5 text-center">
                    <img src="assets/img/about/zha.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">
                            Zha Lim
                        </h5>
                        <p class="card-text">Public Relation</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-outline-default mb-5 text-center">
                    <img src="assets/img/about/rafi.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">
                            Mohamad Rafi Randoni
                        </h5>
                        <p class="card-text">Lead Debug and Testing, Library Development</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-outline-default mb-5 text-center">
                    <img src="assets/img/about/dadang.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">
                            Dadang Nurjaman
                        </h5>
                        <p class="card-text">Library Development, Document Writer</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="contributor-team" class="section-basic">
    <div class="container">
        <h2 class="section-basic-heading">
            Contributor Team
        </h2>
        <div class="team-carousel owl-carousel mt-5">
            <div class="item">
                <div class="card card-outline-default mb-5 text-center">
                    <img src="assets/img/about/yudi.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">
                            Yudi Primaputra
                        </h5>
                        <p class="card-text">Document Editor</p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="card card-outline-default mb-5 text-center">
                    <img src="assets/img/about/viktor.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">
                            Viktor Kristian
                        </h5>
                        <p class="card-text">IT Support</p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="card card-outline-default mb-5 text-center">
                    <img src="assets/img/about/oriza.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">
                            Ahmad Oriza
                        </h5>
                        <p class="card-text">Press Release</p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="card card-outline-default mb-5 text-center">
                    <img src="assets/img/about/arif.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">
                            Arif
                        </h5>
                        <p class="card-text">Debug and Testing, Library Developer</p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="card card-outline-default mb-5 text-center">
                    <img src="assets/img/about/mega.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">
                            Mega Imam Buchori
                        </h5>
                        <p class="card-text">Document Writer</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>