<div class="static-slider static-slider-type-1" style="background-image:url(assets/img/multipurpose/bg-color.jpg)">
    <div class="container">
        <div class="row justify-content-center ">
            <div class="col-md-8 align-self-center text-center" data-aos="fade-right" data-aos-duration="1200">
                <h1 class="title text-light text-uppercase">Features 1-10</h1>
                <h5 class="text-light font-weight-normal">With Infinite Multipurpose, you can create everything, weather its Landing page, Complete Website, Lead generation or Coming soon etc.</h5>
            </div>
        </div>
    </div>
</div>

<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features 1</h1>
                <h6 class="subtitle">Below is features section. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-4">
                <div class="feature1-box">
                    <div class="card card-shadow border-0" data-aos="fade-right" data-aos-duration="1200">
                        <div class="card-body text-center">
                            <div class="feature-icon-space"><img src="./assets/img/logo/logo-50px.png" alt="Infinite Multipurpose" /></div>
                            <h5 class="font-weight-normal">Retargeting Market</h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature1-box">
                    <div class="card card-shadow border-0" data-aos="fade-up" data-aos-duration="1200">
                        <div class="card-body text-center">
                            <div class="feature-icon-space"><img src="./assets/img/logo/logo-50px.png" alt="Infinite Multipurpose" /></div>
                            <h5 class="font-weight-normal">Fruitful Results</h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature1-box">
                    <div class="card card-shadow border-0" data-aos="fade-left" data-aos-duration="1200">
                        <div class="card-body text-center">
                            <div class="feature-icon-space"><img src="./assets/img/logo/logo-50px.png" alt="Infinite Multipurpose" /></div>
                            <h5 class="font-weight-normal">Instant Solutions</h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 mt-5 text-center">
                <a class="btn btn-success btn-lg" href="javascript:void(0);">View More</a>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features 2</h1>
                <h6 class="subtitle">Below is features section. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-md-4">
                <div class="feature2-box">
                    <div class="card card-shadow border-0" data-aos="flip-left" data-aos-duration="1200">
                        <img class="card-img-top" src="assets/img/hello/cms-boilerplate.jpg" alt="Infinite Multipurpose" />
                        <div class="card-body text-center">
                            <h5 class="font-weight-normal">Retargeting Market</h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature2-box">
                    <div class="card card-shadow border-0" data-aos="flip-up" data-aos-duration="1200">
                        <img class="card-img-top" src="assets/img/hello/api-boilerplate.jpg" alt="Infinite Multipurpose" />
                        <div class="card-body text-center">
                            <h5 class="font-weight-normal">Fruitful Results</h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature2-box">
                    <div class="card card-shadow border-0" data-aos="flip-right" data-aos-duration="1200">
                        <img class="card-img-top" src="assets/img/hello/app-boilerplate.jpg" alt="Infinite Multipurpose" />
                        <div class="card-body text-center">
                            <h5 class="font-weight-normal">Instant Solutions</h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features 3</h1>
                <h6 class="subtitle">Below is features section. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-6">
                <div class="feature3-box">
                    <div class="card card-shadow border-0" data-aos="fade-right" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space align-self-center">
                                <i class="fas fa-sync text-primary"></i>
                            </div>
                            <div class="align-self-center">
                                <h5 class="font-weight-normal"><a href="javascript:void(0)" class="link">Instant Solutions</a></h5>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="feature3-box">
                    <div class="card card-shadow border-0" data-aos="fade-left" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space align-self-center">
                                <i class="fas fa-clock text-primary"></i></div>
                            <div class="align-self-center">
                                <h5 class="font-weight-normal"><a href="javascript:void(0)" class="link">Powerful Techniques</a></h5>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="feature3-box">
                    <div class="card card-shadow border-0" data-aos="fade-right" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space align-self-center">
                                <i class="fas fa-smile text-primary"></i>
                            </div>
                            <div class="align-self-center">
                                <h5 class="font-weight-normal"><a href="javascript:void(0)" class="link">100% Satisfaction</a></h5>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="feature3-box">
                    <div class="card card-shadow border-0" data-aos="fade-left" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space align-self-center">
                                <i class="fas fa-file text-primary"></i></div>
                            <div class="align-self-center">
                                <h5 class="font-weight-normal"><a href="javascript:void(0)" class="link">Retargeting Market</a></h5>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features 4</h1>
                <h6 class="subtitle">Below is features section. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-md-6">
                <div class="feature4-box">
                    <div class="card border-0" data-aos="zoom-out-right" data-aos-duration="1200">
                        <div class="card-body">
                            <div class="feature-icon-round bg-info"><i class="fas fa-arrow-alt-circle-down"></i></div>
                            <h5 class="font-weight-normal">Instant Solutions</h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tristique pellentesque ipsum.</p>
                            <a href="javascript:void(0);" class="link text-primary">Check the Feature</a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="feature4-box">
                    <div class="card border-0" data-aos="zoom-out-left" data-aos-duration="1200">
                        <div class="card-body">
                            <div class="feature-icon-round bg-info"><i class="fas fa-arrow-alt-circle-up"></i></div>
                            <h5 class="font-weight-normal">Powerful Techniques </h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tristique pellentesque ipsum. </p>
                            <a class="link text-primary" href="javascript:void(0);">Check the Feature</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features 5</h1>
                <h6 class="subtitle">Below is features section. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-right" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary fas fa-clock"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">Instant Solutions</a></h6>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-down" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary fas fa-info-circle "></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">Powerful Tech </a></h6>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-left" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary fas fa-star"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">100% Satisfaction </a></h6>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-right" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary fas fa-users"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">Targeting Market</a></h6>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-up" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary fas fa-check-circle"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">Goal Achievement </a></h6>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-left" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary  fas fa-mobile-alt"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">Fully Responsive</a></h6>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features 6</h1>
                <h6 class="subtitle">Below is features section. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-md-4">
                <div class="feature6-box">
                    <div class="card bg-success text-white" data-aos="fade-right" data-aos-duration="1200">
                        <div class="card-body">
                            <h6 class="font-weight-normal text-white">Retargeting Market</h6>
                            <p class="mt-3">Lorem ipsum dolor sit amet, consecte tuam porttitor, nunc et fringilla.</p>
                            <a href="javascript:void" class="link">Learn More <i class="fas fa-angle-double-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature6-box">
                    <div class="card bg-info text-white" data-aos="fade-down" data-aos-duration="1200">
                        <div class="card-body">
                            <h6 class="font-weight-normal text-white">Instant Solutions</h6>
                            <p class="mt-3">Lorem ipsum dolor sit amet, consecte tuam porttitor, nunc et fringilla.</p>
                            <a href="javascript:void" class="link">Learn More <i class="fas fa-angle-double-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature6-box">
                    <div class="card bg-danger text-white" data-aos="fade-left" data-aos-duration="1200">
                        <div class="card-body">
                            <h6 class="font-weight-normal text-white">Powerful Techniques</h6>
                            <p class="mt-3">Lorem ipsum dolor sit amet, consecte tuam porttitor, nunc et fringilla.</p>
                            <a href="javascript:void" class="link">Learn More <i class="fas fa-angle-double-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features 7</h1>
                <h6 class="subtitle">Below is features section. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-4">
                <div class="feature7-box">
                    <div class="" data-aos="flip-left" data-aos-duration="1200">
                        <img class="rounded img-fluid" src="assets/img/hello/api-boilerplate.jpg" alt="Infinite Multipurpose" />
                        <div class="mt-3">
                            <h5 class="font-weight-normal">Retargeting Market</h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            <a href="javascript:void(0)" class="link">Learn More <i class="fas fa-angle-double-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature7-box">
                    <div class="" data-aos="flip-up" data-aos-duration="1200">
                        <img class="rounded img-fluid" src="assets/img/hello/app-boilerplate.jpg" alt="Infinite Multipurpose" />
                        <div class="mt-3">
                            <h5 class="font-weight-normal">Fruitful Results</h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            <a href="javascript:void(0)" class="link">Learn More <i class="fas fa-angle-double-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="feature7-box">
                    <div class="" data-aos="flip-right" data-aos-duration="1200">
                        <img class="rounded img-fluid" src="assets/img/hello/cms-boilerplate.jpg" alt="Infinite Multipurpose" />
                        <div class="mt-3">
                            <h5 class="font-weight-normal">Instant Solutions</h5>
                            <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            <a href="javascript:void(0)" class="link">Learn More <i class="fas fa-angle-double-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features 8</h1>
                <h6 class="subtitle">Below is features section. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>

        <div class="row mt-3 feature8">
            <div class="col-lg-6">
                <small class="text-info">Success Stories</small>
                <h4>Re-Targeting gets easier with WrapKit</h4>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet.</p>
                <ul class="list-block mb-3">
                    <li><i class="fas fa-check-circle text-info mb-2"></i> Powerful and Faster Results for your site</li>
                    <li><i class="fas fa-check-circle text-info mb-2"></i> Make your site in no-time with your Bootstrap WrapKit</li>
                    <li><i class="fas fa-check-circle text-info mb-2"></i> Tons of Features and Elements available here</li>
                    <li><i class="fas fa-check-circle text-info mb-2"></i> What are you wait for? Go and Get it.</li>
                </ul>
                <a class="btn btn-info" href="javascript:void(0);">Learn More <i class="fas fa-angle-double-right"></i></a>
            </div>
            <div class="col-lg-6">
                <div class="p-3">
                    <img src="assets/img/hello/app-boilerplate.jpg" alt="Infinite Multipurpose" class="img-fluid img-shadow" data-aos="flip-right" data-aos-duration="1200" />
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features 9</h1>
                <h6 class="subtitle">Below is features section. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-6">
                <div class="feature9-box">
                    <div class="card border-0" data-aos="fade-right" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="align-self-center">
                                <h2 class="font-weight-normal">Wrap Seo Digital Marketing Agency</h2>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="feature9-box">
                    <div class="card border-0" data-aos="fade-left" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space align-self-center"><i class="fas fa-desktop text-info"></i></div>
                            <div class="align-self-center">
                                <h5 class="font-weight-normal"><a href="javascript:void(0)" class="link">Online Marketer</a></h5>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="feature9-box">
                    <div class="card border-0" data-aos="fade-right" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space align-self-center"><i class="fas fa-cloud text-info"></i></div>
                            <div class="align-self-center">
                                <h5 class="font-weight-normal"><a href="javascript:void(0)" class="link">Digital World</a></h5>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="feature9-box">
                    <div class="card border-0" data-aos="fade-left" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space align-self-center"><i class="fas fa-handshake text-info"></i></div>
                            <div class="align-self-center">
                                <h5 class="font-weight-normal"><a href="javascript:void(0)" class="link">Meet the Team</a></h5>
                                <p class="mt-3">You can relay on our amazing features list and also our customer services will be great experience.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>

<section class="pb-0">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features 10</h1>
                <h6 class="subtitle">Below is features section. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-lg-4 bg-secondary">
            <div class="feature10-box text-center">
                <div class="mb-3"><i class="fas fa-user"></i></div>
                <small>Awesome Service</small>
                <h4 class="box-title">New Lead Generation</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellent esque dignissim eros a sapien tempus, ut eleifend neque convallis.</p>
                <a class="btn btn-outline-light btn-lg" href="javascript:void(0)">View Feature</a>
            </div>
        </div>
        
        <div class="col-lg-4 bg-primary">
            <div class="feature10-box text-center">
                <div class="mb-3"><i class="fas fa-building"></i></div>
                <small>Awesome Service</small>
                <h4 class="box-title">Constructive Planning</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellent esque dignissim eros a sapien tempus, ut eleifend neque convallis.</p>
                <a class="btn btn-outline-light btn-lg" href="javascript:void(0)">View Feature</a>
            </div>
        </div>
        
        <div class="col-lg-4 bg-warning">
            <div class="feature10-box text-center">
                <div class="mb-3"><i class="fas fa-star"></i></div>
                <small>Well Focused</small>
                <h4 class="box-title">Powerful Services</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellent esque dignissim eros a sapien tempus, ut eleifend neque convallis.</p>
                <a class="btn btn-outline-light btn-lg" href="javascript:void(0)">View Feature</a>
            </div>
        </div>
    </div>
</section>