<div class="static-slider static-slider-type-1" style="background-image:url(assets/img/multipurpose/bg-color.jpg)">
    <div class="container">
        <div class="row justify-content-center ">
            <div class="col-md-8 align-self-center text-center" data-aos="fade-right" data-aos-duration="1200">
                <h1 class="title text-light text-uppercase">Form Banner</h1>
                <h5 class="text-light font-weight-normal">With Infinite Multipurpose, you can create everything, weather its Landing page, Complete Website, Lead generation or Coming soon etc.</h5>
            </div>
        </div>
    </div>
</div>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Form Banner 1</h1>
                <h6 class="subtitle">Below is form banner. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
	<div class="static-slider static-slider-type-1" style="background-image:url(assets/img/multipurpose/banner-cityview.jpg)">
	    <div class="container">
	        <div class="row justify-content-center">
	            <div class="col-md-8 align-self-center text-center" data-aos="fade-right" data-aos-duration="1200">
	                <h1 class="title text-light text-uppercase">Form Banner 1</h1>
	                <h5 class="text-light font-weight-normal">With Infinite Multipurpose, you can create everything, weather its Landing page, Complete Website, Lead generation or Coming soon etc.</h5>
	            </div>

	            <div class="col-md-12 align-self-center" data-aos="fade-right" data-aos-duration="1200">
	                <div class="card mt-3">
                        <div class="card-body">
                            <form>
                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label>Dari</label>
                                            <select class="form-control custom-select select2">
                                                <option value="">Denpasar</option>
                                                <option value="">Malang</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label>Ke</label>
                                            <select class="form-control custom-select select2">
                                                <option value="">Denpasar</option>
                                                <option value="">Malang</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-sm-4">
                                        <ul class="nav nav-tabs" role="tablist">
                                            <li class="nav-item">
                                                <a class="nav-link active" data-toggle="tab" href="#oneway" role="tab" aria-selected="true">Sekali Jalan</a>
                                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#twoway" role="tab" aria-selected="false">Pulang Pergi</a>
                                            </li>
                                        </ul>
                                        <div class="tab-content border-0" id="departure">
                                            <div class="tab-pane fade show active" id="oneway" role="tabpanel">
                                                <div class="form-group">
                                                    <div class="input-group">
                                                        <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="tab-pane fade" id="twoway" role="tabpanel">
                                                <div class="form-group">
                                                    <div class="input-group">
                                                        <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="input-group">
                                                        <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="col-sm-4 border-0">
                                        <div class="form-group">
                                            <label>Dewasa</label>
                                            <select class="form-control custom-select">
                                                <option value="">1</option>
                                                <option value="">2</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label>Bayi</label>
                                            <select class="form-control custom-select">
                                                <option value="">0</option>
                                                <option value="">1</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-success btn-block"><i class="fa fa-search"></i> Cari Tiket</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
	            </div>
	        </div>
	    </div>
	</div>
</section>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Form Banner 2</h1>
                <h6 class="subtitle">Below is form banner. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
	<div class="static-slider static-slider-type-1 py-5" style="background-image:url(assets/img/multipurpose/banner-cityview.jpg)">
	    <div class="container">
	        <div class="row align-items-center justify-content-center">
	            <div class="col-md-7 col-lg-5" data-aos="fade-right" data-aos-duration="1200">
	                <form class="form-banner2">
                    	<ul class="nav nav-tabs nav-fill bg-white" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#oneway2" role="tab" aria-selected="true">Sekali Jalan</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#twoway2" role="tab" aria-selected="false">Pulang Pergi</a>
                            </li>
                        </ul>
                        <div class="tab-content bg-white border-0 mb-0">
                            <div class="tab-pane fade show active" id="oneway2" role="tabpanel">
                            	<div class="form-row">
                                    <div class="col-sm-6">
                                    	<div class="form-group">
                                            <label>Dari</label>
                                            <select class="form-control custom-select select2">
                                                <option value="">Denpasar</option>
                                                <option value="">Malang</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                    	<div class="form-group">
                                            <label>Ke</label>
                                            <select class="form-control custom-select select2">
                                                <option value="">Denpasar</option>
                                                <option value="">Malang</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                	<label>Pergi</label>
                                    <div class="input-group">
                                        <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-sm-6">
                                    	<div class="form-group">
                                    		<label>Dewasa</label>
                                            <select class="form-control custom-select">
                                                <option value="">1</option>
                                                <option value="">2</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Bayi</label>
                                            <select class="form-control custom-select">
                                                <option value="">0</option>
                                                <option value="">1</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-block"><i class="fa fa-search"></i> Cari Tiket</button>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="twoway2" role="tabpanel">
                                <div class="form-row">
                                    <div class="col-sm-6">
                                    	<div class="form-group">
                                            <label>Dari</label>
                                            <select class="form-control custom-select select2">
                                                <option value="">Denpasar</option>
                                                <option value="">Malang</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                    	<div class="form-group">
                                            <label>Ke</label>
                                            <select class="form-control custom-select select2">
                                                <option value="">Denpasar</option>
                                                <option value="">Malang</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-sm-6">
		                                <div class="form-group">
		                                	<label>Pergi</label>
		                                    <div class="input-group">
		                                        <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
		                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="col-sm-6">
		                                <div class="form-group">
		                                	<label>Pulang</label>
		                                    <div class="input-group">
		                                        <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy">
		                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
                                <div class="form-row">
                                    <div class="col-sm-6">
                                    	<div class="form-group">
                                    		<label>Dewasa</label>
                                            <select class="form-control custom-select">
                                                <option value="">1</option>
                                                <option value="">2</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Bayi</label>
                                            <select class="form-control custom-select">
                                                <option value="">0</option>
                                                <option value="">1</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-block"><i class="fa fa-search"></i> Cari Tiket</button>
                                </div>
                            </div>
                        </div>
                    </form>
	            </div>
	            <div class="col-md-4 col-lg-5" data-aos="fade-left" data-aos-duration="1200">
	            	<div id="carousel-banner-2" class="carousel slide" data-ride="carousel">
					    <ol class="carousel-indicators">
					        <li data-target="#carousel-banner-2" data-slide-to="0" class="active"></li>
					        <li data-target="#carousel-banner-2" data-slide-to="1"></li>
					    </ol>
					    <div class="carousel-inner">
					        <div class="carousel-item active">
					            <img class="d-block w-100" src="assets/img/hello/api-boilerplate.jpg" alt="First slide">
					        </div>
					        <div class="carousel-item">
					            <img class="d-block w-100" src="assets/img/hello/app-boilerplate.jpg" alt="Second slide">
					        </div>
					    </div>
					    <a class="carousel-control-prev" href="#carousel-banner-2" role="button" data-slide="prev">
						    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
						    <span class="sr-only">Previous</span>
						  </a>
					    <a class="carousel-control-next" href="#carousel-banner-2" role="button" data-slide="next">
						    <span class="carousel-control-next-icon" aria-hidden="true"></span>
						    <span class="sr-only">Next</span>
						  </a>
					</div>
	            </div>
	        </div>
	    </div>
	</div>
</section>