<div class="static-slider static-slider-type-1" style="background-image:url(assets/img/multipurpose/bg-color.jpg)">
    <div class="container">
        <div class="row justify-content-center ">
            <div class="col-md-8 align-self-center text-center" data-aos="fade-right" data-aos-duration="1200">
                <h1 class="title text-light text-uppercase">Navigations 1-8</h1>
                <h5 class="text-light font-weight-normal">With Infinite Multipurpose, you can create everything, weather its Landing page, Complete Website, Lead generation or Coming soon etc.</h5>
            </div>
        </div>
    </div>
</div>
<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Navigation 1</h1>
                <h6 class="subtitle">Below is simple header. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <!-- Header 1 code -->
    <nav class="navbar navbar-expand-md navbar-dark navbar-type-1 bg-white" id="page-navigation-multipurpose">
        <div class="container position-relative">
            <a class="navbar-brand" href="#">
                <img class="color d-none" src="assets/img/logo-multipurpose.png" alt="Infinite Multipurpose" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="header1">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item dropdown mega-dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Demos
                        </a>
                        <div class="dropdown-menu border-0 animated fadeInUp">
                            <div class="row">
                                <div class="col-lg-3 inside-bg d-md-block d-lg-block d-none">
                                    <div class="bg-img" style="background-image:url(assets/img/bg-galaxy.jpg)">
                                        <h4 class="text-white font-weight-normal">Most Powerfull Bootstrap 4 UI Kit</h4>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-md-6">
                                    <ul>
                                        <li><h6>Niche Homepages</h6></li>
                                        <li><a href="#">Business</a></li>
                                        <li><a href="#" target="_blank">Creative</a></li>
                                        <li><a href="#" target="_blank">Charity</a></li>
                                        <li><a href="#" target="_blank">Health & Medical</a></li>
                                        <li><a href="#" target="_blank">Software Application</a></li>
                                        <li><a href="#" target="_blank">Real Estate</a></li>
                                        <li><a href="#" target="_blank">Restaurant</a></li>
                                        
                                    </ul>
                                </div>
                                <div class="col-lg-2 col-md-6">
                                    <ul class="list-style-none">
                                        <li><h6>&nbsp;</h6></li>
                                        <li><a href="#" target="_blank">Web-Agency</a></li>
                                        <li><a href="#" target="_blank">Fitness</a></li>
                                        <li><a href="#" target="_blank">Accounting</a></li>
                                        <li><a href="#" target="_blank">One Page</a></li>
                                        <li><a href="#" target="_blank">Marketing / SEO</a></li>
                                        <li><a href="#" target="_blank">Industrial</a></li>
                                        <li><a href="#" target="_blank">Cryptocurrency</a></li>
                                        
                                    </ul>
                                </div>
                                <div class="col-lg-2 col-md-6">
                                    <ul class="list-style-none">
                                        <li><h6>Landing Pages</h6></li>
                                        <li><a href="#" target="_blank">App Landing</a></li>
                                        <li><a href="#" target="_blank">Health & Medical</a></li>
                                        <li><a href="#" target="_blank">Personal Landing</a></li>
                                        <li><a href="#" target="_blank">Form Landing</a></li>
                                        <li><a href="#" target="_blank">Appointment Landing</a></li>
                                        <li><a class="text-muted">More Coming soon...</a></li>
                                    </ul>
                                </div>
                                <div class="col-lg-3 col-md-6">
                                    <ul class="list-style-none">
                                        <li><h6>Freelancer / Portfolio</h6></li>
                                        <li><a href="#" target="_blank">Freelancer 1</a></li>
                                        <li><a href="#" target="_blank">Freelancer 2</a></li>
                                        <li><a href="#" target="_blank">Photographer Light</a></li>
                                        <li><a href="#" target="_blank">Photographer Dark</a></li>
                                        <li><a href="#" target="_blank">Comming Soon</a></li>
                                    </ul>
                                </div>
                                
                            </div>
                        </div>
                    </li>
                    <li class="nav-item dropdown mega-dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Sections
                        </a>
                        <div class="dropdown-menu border-0 animated fadeInUp">
                            <div class="row">
                                <div class="col-lg-4 inside-bg hidden-md-down">
                                    <div class="bg-img" style="background-image:url(assets/img/bg-galaxy.jpg)">
                                        <h3 class="text-white font-weight-normal">Create anything <br/>with our amazing <br/>sections</h3>
                                    </div>
                                </div>
                                
                                <div class="col-lg-2 col-md-4">
                                    <ul class="list-style-none">
                                        <li><h6>Headers &amp; Footers</h6></li>
                                        <li><a href="#" target="_blank">Banners</a></li>
                                        <li><a href="#" target="_blank">Form Banners</a></li>
                                        <li><a href="#" target="_blank">Navigation 1-10</a></li>
                                        <li><a href="#" target="_blank">Navigation 11-20</a></li>
                                        <li><a href="#" target="_blank">Footers</a></li>
                                        <li><a href="#" target="_blank">Call to Actions</a></li>
                                    </ul>
                                </div>
                                <div class="col-lg-1 col-md-4">
                                    <ul class="list-style-none">
                                        <li><h6>Sliders</h6></li>
                                        <li><a href="#" target="_blank">Slider1</a></li>
                                        <li><a href="#" target="_blank">Slider2</a></li>
                                        <li><a href="#" target="_blank">Slider3</a></li>
                                        <li><a href="#" target="_blank">Slider4</a></li>
                                        <li><a href="#" target="_blank">Slider5</a></li>
                                    </ul>
                                </div>
                                <div class="col-lg-1 col-md-4">
                                    <ul class="list-style-none">
                                        <li><h6>&nbsp;</h6></li>
                                        <li><a href="#" target="_blank">Slider6</a></li>
                                        <li><a href="#" target="_blank">Slider7</a></li>
                                        <li><a href="#" target="_blank">Slider8</a></li>
                                        <li><a href="#" target="_blank">Slider9</a></li>
                                        <li><a href="#" target="_blank">Slider10</a></li>
                                    </ul>
                                </div>
                                <div class="col-lg-2 col-md-4">
                                    <ul class="list-style-none">
                                        <li><h6>Other Sections</h6></li>
                                        <li><a href="#" target="_blank">Contacts</a></li>
                                        <li><a href="#" target="_blank">Blogs</a></li>
                                        <li><a href="#" target="_blank">Pricing</a></li>
                                        <li><a href="#" target="_blank">Teams</a></li>
                                        <li><a href="#" target="_blank">Testimonials</a></li>
                                    </ul>
                                </div>
                                <div class="col-lg-2 col-md-4">
                                    <ul class="list-style-none">
                                        <li><h6>Features</h6></li>
                                        <li><a href="#" target="_blank">Features 1-10</a></li>
                                        <li><a href="#" target="_blank">Features 11-20</a></li>
                                        <li><a href="#" target="_blank">Features 21-30</a></li>
                                        <li><a href="#" target="_blank">Features 31-40</a></li>
                                        <li><a href="#" target="_blank">Features 41-50</a></li>
                                    </ul>
                                </div>
                                
                            </div>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Pages
                        </a>
                        <ul class="border-0 dropdown-menu animated fadeInUp">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                            <li class="divider" role="separator"></li>
                            <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" data-toggle="dropdown" href="#">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                                <ul class="dropdown-menu border-0 menu-right">
                                    <li><a class="dropdown-item" href="#">Action</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                    <li class="divider" role="separator"></li>
                                    <li><a class="dropdown-item" href="#">Separated link</a></li>
                                    <li class="divider" role="separator"></li>
                                    <li><a class="dropdown-item" href="#">One more separated link</a></li>
                                </ul>
                            </li>
                            <li><a class="dropdown-item" href="#">Separated link</a></li>
                            <li class="divider" role="separator"></li>
                            <li><a class="dropdown-item" href="#">One more separated link</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="btn btn-outline-success" href="#">Hire Me</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Header 1 code -->
</section>
<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Navigation 2</h1>
                <h6 class="subtitle">Below is simple header. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <!-- Header 2 code -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-type-2">
        <div class="container position-relative">
            <a class="navbar-brand" href="#"><img src="assets/img/logo-multipurpose.png" alt="Infinite Multipurpose" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header2" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="header2">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About Me</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Work</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="h1-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Services
                        </a>
                        <ul class="border-0 dropdown-menu animated fadeInUp">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                            <li class="divider" role="separator"></li>
                            <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" data-toggle="dropdown" href="#">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                                <ul class="dropdown-menu border-0 menu-right">
                                    <li><a class="dropdown-item" href="#">Action</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                    <li class="divider" role="separator"></li>
                                    <li><a class="dropdown-item" href="#">Separated link</a></li>
                                    <li class="divider" role="separator"></li>
                                    <li><a class="dropdown-item" href="#">One more separated link</a></li>
                                </ul>
                            </li>
                            <li><a class="dropdown-item" href="#">Separated link</a></li>
                            <li class="divider" role="separator"></li>
                            <li><a class="dropdown-item" href="#">One more separated link</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="#">Freebies</a></li>
                    <li class="nav-item"><a class="btn btn-outline-success" href="#">Hire Me</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Header 2 code -->
</section>
<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Navigation 3</h1>
                <h6 class="subtitle">Below is simple header. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <div class="header-overlay">
        <!-- Header 3 code -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-type-3">
            <div class="container position-relative">
                <a class="navbar-brand" href="#"><img src="assets/img/logo-multipurpose-white.png" alt="Infinite Multipurpose" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header3" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="header3">
                    <ul class="navbar-nav">
                        <li class="nav-item active"><a class="nav-link" href="#">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="h2-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Product
                            </a>
                            <ul class="dropdown-menu animated fadeInUp">
                                <li>
                                    <a class="dropdown-item" href="#">Action</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">Another action</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </li>
                                <li class="divider" role="separator"></li>
                                <li>
                                    <a class="dropdown-item" href="#">Separated link</a>
                                </li>
                                <li class="divider" role="separator"></li>
                                <li>
                                    <a class="dropdown-item" href="#">One more separated link</a>
                                </li>
                                <li class="dropdown-submenu"> 
                                    <a class="dropdown-toggle dropdown-item" data-toggle="dropdown" href="#">
                                        Dropdown <i class="fa fa-angle-right ml-auto"></i>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                        <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" href="#" data-toggle="dropdown">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                                            <ul class="nav navbar-nav dropdown-menu">
                                                <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" href="#" data-toggle="dropdown">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                                                    <ul class="dropdown-menu">
                                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                                        <li class="divider" role="separator"></li>
                                                        <li><a class="dropdown-item" href="#">Separated link</a></li>
                                                        <li class="divider" role="separator"></li>
                                                        <li><a class="dropdown-item" href="#">One more separated link</a></li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="#">Features</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">About Us</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" href="#"><i class="fa fa-comments"></i> Need help?</a></li>
                        <li class="nav-item active"><a class="nav-link" href="#">Login</a></li>
                        <li class="nav-item"><a class="btn btn-rounded btn-dark" href="#">Sign up</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Header 3 code -->
    </div>
    <div class="row">
        <div class="col-md-12 bg-success">
            <div class="p-5 mb-5"></div>
            <div class="p-5 mb-5"></div>
        </div>
    </div>
</section>
<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Navigation 4</h1>
                <h6 class="subtitle">Below is simple header. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <div class="header-overlay">
        <!-- Header 4 code -->
        <div class="navbar-type-4-topbar bg-white">
            <div class="container">
                <div class="row">
                    <div class="col-md-5">
                        <ul class="list-inline">
                            <li><a href="mailto:info@yourdomain.com"><i class="icon-Mail info-icon"></i> info@wrappixel.com</a></li>
                        </ul>
                    </div>
                    <div class="col-md-7 text-right">
                        <ul class="list-inline">
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fab fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fab fa-google-plus"></i></a></li>
                            <li><a><span class="vdevider"></span></a></li>
                            <li><a href="#"><i class="fas fa-phone"></i> +62 123 4567</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-type-4">
            <div class="container position-relative">
                <a class="navbar-brand" href="#">
                    <img src="assets/img/logo-multipurpose.png" alt="Infinite Multipurpose" />
                    <br>
                    <img class="logo-text" src="assets/img/teguh-rianto-autograf.png">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header4" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="header4">
                    <ul class="navbar-nav">
                        <li class="nav-item active"><a class="nav-link" href="#">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="h2-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Product
                            </a>
                            <ul class="dropdown-menu animated fadeInUp">
                                <li>
                                    <a class="dropdown-item" href="#">Action</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">Another action</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </li>
                                <li class="divider" role="separator"></li>
                                <li>
                                    <a class="dropdown-item" href="#">Separated link</a>
                                </li>
                                <li class="divider" role="separator"></li>
                                <li>
                                    <a class="dropdown-item" href="#">One more separated link</a>
                                </li>
                                <li class="dropdown-submenu"> 
                                    <a class="dropdown-toggle dropdown-item" data-toggle="dropdown" href="#">
                                        Dropdown <i class="fa fa-angle-right ml-auto"></i>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                        <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" href="#" data-toggle="dropdown">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                                            <ul class="nav navbar-nav dropdown-menu">
                                                <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" href="#" data-toggle="dropdown">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                                                    <ul class="dropdown-menu">
                                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                                        <li class="divider" role="separator"></li>
                                                        <li><a class="dropdown-item" href="#">Separated link</a></li>
                                                        <li class="divider" role="separator"></li>
                                                        <li><a class="dropdown-item" href="#">One more separated link</a></li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="#">Features</a></li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="nav-link" href="#"><i class="fa fa-comments"></i> Need help?</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Sign up</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Header 4 code -->
    </div>
    <div class="row">
        <div class="col-md-12 bg-info">
            <div class="p-5 mb-5"></div>
            <div class="p-5 mb-5"></div>
        </div>
    </div>
</section>
<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Navigation 5</h1>
                <h6 class="subtitle">Below is simple header. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <!-- Header 5 code -->
    <div class="navbar-type-5-topbar">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-type-5-nav">
                <a class="d-lg-none d-block">Navigation</a>
                <button class="navbar-toggler text-white" type="button" data-toggle="collapse" data-target="#header5" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="header5">
                    <ul class="navbar-nav">
                        <li class="nav-item active"><a class="nav-link" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Causes</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Become Volunteer</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Pages
                            </a>
                            <ul class="border-0 dropdown-menu animated fadeInUp">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                                <li class="divider" role="separator"></li>
                                <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" href="#" data-toggle="dropdown">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                                    <ul class="dropdown-menu b-none">
                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                        <li class="divider" role="separator"></li>
                                        <li><a class="dropdown-item" href="#">Separated link</a></li>
                                        <li class="divider" role="separator"></li>
                                        <li><a class="dropdown-item" href="#">One more separated link</a></li>
                                    </ul>
                                </li>
                                <li><a class="dropdown-item" href="#">Separated link</a></li>
                                <li class="divider" role="separator"></li>
                                <li><a class="dropdown-item" href="#">One more separated link</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="#">Shop</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown search">
                            <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-search"></i></a>
                            <div class="dropdown-menu border-0 dropdown-menu-right animated fadeInDown">
                                <input class="form-control" type="text" placeholder="Type & hit enter" />
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg bg-white navbar-type-5">
        <div class="container">
            <a class="navbar-brand">
                <img src="assets/img/logo-multipurpose.png" alt="Infinite Multipurpose"/>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header5-info"aria-expanded="false" aria-label="Toggle navigation">
                <span class="fas fa-ellipsis-v"></span>
            </button>
            <div class="collapse navbar-collapse" id="header5-info">
                <ul class="navbar-nav ml-auto text-uppercase">
                    <li class="nav-item">
                        <a class="nav-link">
                            <h2 class="mb-0 mr-2">
                                <i class="fas fa-envelope"></i>
                            </h2>
                            <div>
                                <small>Email us at</small>
                                <h6>info@yourdomain.com</h6>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">
                            <h2 class="mb-0 mr-2">
                                <i class="fas fa-phone"></i>
                            </h2>
                            <div>
                                <small>CALL US NOW</small>
                                <h6>703 (123) 4567</h6>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item donate-btn">
                        <a href="#" class="btn btn-outline-danger">Donate now</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Header 5 code -->
</section>
<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Navigation 6</h1>
                <h6 class="subtitle">Below is simple header. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <div class="header-overlay">
        <!-- Header 6 code -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-type-6">
            <div class="container position-relative">
                <a class="navbar-brand" href="#"><img src="assets/img/logo-multipurpose-white.png" alt="Infinite Multipurpose" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header6" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse text-uppercase" id="header6">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active"><a class="nav-link" href="#">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="h2-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Product
                            </a>
                            <ul class="dropdown-menu animated fadeInUp">
                                <li>
                                    <a class="dropdown-item" href="#">Action</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">Another action</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </li>
                                <li class="divider" role="separator"></li>
                                <li>
                                    <a class="dropdown-item" href="#">Separated link</a>
                                </li>
                                <li class="divider" role="separator"></li>
                                <li>
                                    <a class="dropdown-item" href="#">One more separated link</a>
                                </li>
                                <li class="dropdown-submenu"> 
                                    <a class="dropdown-toggle dropdown-item" data-toggle="dropdown" href="#">
                                        Dropdown <i class="fa fa-angle-right ml-auto"></i>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                        <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" href="#" data-toggle="dropdown">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                                            <ul class="nav navbar-nav dropdown-menu">
                                                <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" href="#" data-toggle="dropdown">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                                                    <ul class="dropdown-menu">
                                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                                        <li class="divider" role="separator"></li>
                                                        <li><a class="dropdown-item" href="#">Separated link</a></li>
                                                        <li class="divider" role="separator"></li>
                                                        <li><a class="dropdown-item" href="#">One more separated link</a></li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="#">Features</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">About Us</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
                    </ul>
                    <div class="rounded-button">
                        <a href="#">Login</a> - OR - <a href="#">Register</a>
                    </div>
                </div>
            </div>
        </nav>
        <!-- End Header 6 code -->
    </div>
    <div class="row">
        <div class="col-md-12 bg-dark">
            <div class="p-5 mb-5"></div>
            <div class="p-5 mb-5"></div>
        </div>
    </div>
</section>
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Navigation 7</h1>
                <h6 class="subtitle">Below is simple header. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <div class="header-overlay">
        <!-- Header 7 code -->
        <div class="navbar-type-7-topbar bg-gray">
            <div class="container">
                <div class="d-flex justify-content-between font-14">
                    <div class=" hidden-md-down align-self-center">
                        Welcome to Infinite, Your Solution for All Web Needs
                    </div>
                    <div class="">
                        <ul class="list-inline authentication-box">
                            <li><a href="#">Login </a></li>
                            <li><a href="#">Create Account </a></li>
                            <li><a href="#"><i class="fas fa-shopping-basket"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-type-7">
            <div class="container position-relative">
                <a class="navbar-brand" href="#"><img src="assets/img/logo-multipurpose.png" alt="Infinite Multipurpose" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header7" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="header7">
                    <ul class="navbar-nav mt-2 mt-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About Me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Work</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="h1-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Services
                            </a>
                            <ul class="border-0 dropdown-menu animated fadeInUp">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                                <li class="divider" role="separator"></li>
                                <li class="dropdown-submenu"> <a class="dropdown-toggle dropdown-item" data-toggle="dropdown" href="#">Dropdown <i class="fa fa-angle-right ml-auto"></i></a>
                                    <ul class="dropdown-menu border-0 menu-right">
                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                        <li class="divider" role="separator"></li>
                                        <li><a class="dropdown-item" href="#">Separated link</a></li>
                                        <li class="divider" role="separator"></li>
                                        <li><a class="dropdown-item" href="#">One more separated link</a></li>
                                    </ul>
                                </li>
                                <li><a class="dropdown-item" href="#">Separated link</a></li>
                                <li class="divider" role="separator"></li>
                                <li><a class="dropdown-item" href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="ml-auto act-buttons">
                        <button class="btn btn-outline-primary">Contact Us</button>
                        <button class="btn btn-outline-danger">Sign Up</button>
                    </div>
                </div>
            </div>
        </nav>
        <!-- End Header 7 code -->
    </div>
    <div class="row">
        <div class="col-md-12 bg-primary">
            <div class="p-5 mb-5"></div>
            <div class="p-5 mb-5"></div>
        </div>
    </div>
</section>
<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Navigation 8</h1>
                <h6 class="subtitle">Below is simple header. You can use any of this header into your webpage, you just need to copy - paste html and css of the header.</h6>
            </div>
        </div>
    </div>
    <div class="header8">
        <div class="container position-relative">
            <!-- Topbar -->
            <div class="navbar-type-8-topbar">
                <div class="d-flex justify-content-between">
                    <div class=" d-md-inline-block d-none align-self-center">
                        Welcome to Infinite, Your Solution for All Web Needs
                    </div>
                    <div class="topbar-btn">
                        <a class="btn btn-success btn-sm" href="#">Free consulations</a>
                    </div>
                </div>
            </div>
            <!-- End Topbar -->
            <!-- Navbar -->
            <div class="navbar-type-8 pb-3 pb-lg-0 justify-content-center">
                <div class="logo-wrapper d-flex align-items-center m-auto">
                    <a href="javascript:void(0)" class="navbar-brand mr-0">
                        <img src="assets/img/logo-multipurpose.png" alt="Infinite Multipurpose" class="img-fluid" />
                    </a>
                </div>
                <button class="btn btn-success btn-circle d-md-none d-block toggler" data-toggle="collapse" data-target="#header8">
                    <i class="fas fa-bars"></i>
                </button>
                <nav class="nav-wrapper" id="header8">
                    <div class="mini-bar">
                        <div class="d-flex justify-content-between">
                            <div class="general-info">
                                <span><i class="fas fa-envelope text-success"></i> info@yourdomain.com</span>
                                <span><i class="fas fa-phone-square text-success"></i> +62-234-6789</span>
                                <span class="d-lg-inline-block d-none"><i class="fa fa-clock-o text-success"></i> 8.00 AM - 6:00PM</span>
                            </div>
                            <div class="social-info d-lg-inline-block d-none">
                                <a href="#"><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-google-plus"></i></a>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="main-nav">
                        <ul>
                            <li class="nav-item"><a href="javascript:void(0)" class="nav-link">Home</a></li>
                            <li class="nav-item"><a href="javascript:void(0)" class="nav-link">SERVICES <i class="fa fa-angle-down ml-2"></i></a>
                                <ul class="animated fadeInUp">
                                    <li><a href="#">Web Development</a></li>
                                    <li><a href="#">Web Designing</a></li>
                                    <li><a href="#">Software Development</a></li>
                                    <li><a href="#">Mobile Developement</a></li>
                                </ul>
                            </li>
                            <li class="nav-item"><a href="javascript:void(0)" class="nav-link">CASE STUDY <i class="fa fa-angle-down ml-2"></i></a>
                                <ul class="animated fadeInUp">
                                    <li><a href="#">Web Development</a></li>
                                    <li><a href="#">Web Designing</a></li>
                                    <li><a href="#">Software Development</a></li>
                                    <li><a href="#">Mobile Developement</a></li>
                                    <li><a href="#">Web Development</a></li>
                                    <li><a href="#">Web Designing</a></li>
                                    <li><a href="#">Software Development</a></li>
                                </ul>
                            </li>
                            <li class="nav-item"><a href="javascript:void(0)" class="nav-link">BLOG</a></li>
                            <li class="nav-item"><a href="javascript:void(0)" class="nav-link">CONTACT</a></li>
                            <li class="nav-item"><a href="javascript:void(0)" class="nav-link">FEATURES</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <div class="bg-primary">
        <div class="p-5 mb-5"></div>
        <div class="p-5 mb-5"></div>
    </div>
</section>