<!DOCTYPE html>
<html>
<head>
    <title>{{ $meta->title }}</title>
	<link rel="stylesheet" type="text/css" href="./assets/app.min.css">
</head>
<body class="multipurpose">

	<div id="page-content" class="page-content">
	    {{ $partials->content }}
	</div>

	<a class="scroll-to-top" href="#top"><i class="fas fa-long-arrow-alt-up"></i>To Top</a>
	<script type="text/javascript" src="./assets/app.min.js"></script>
</body>
</html>