<!DOCTYPE html>
<html>
<head>
    <title>{{ $meta->title }}</title>
    <link rel="icon" type="image/png" href="/assets/icons/launcher-icon-32.png">
	{{ $assets->head }}
</head>
<body class="multipurpose">
	<div id="page-content" class="page-content">
	    {{ $partials->content }}
	</div>

	<a class="scroll-to-top" href="#top"><i class="fas fa-long-arrow-alt-up"></i>To Top</a>
	{{ $assets->body }}
</body>
</html>
