<nav id="page-navigation-multipurpose" class="navbar navbar-expand-lg navbar-dark navbar-type-3">
    <div class="container position-relative">
        <a class="navbar-brand" href="#"><img src="./assets/img/logo/logo-200px.png" alt="O2System Framework" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header3" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="header3">
            <ul class="navbar-nav">
                <li class="nav-item active"><a class="nav-link" href="{{base_url()}}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{{base_url('example')}}">Example</a></li>
                <li class="nav-item"><a class="nav-link" href="{{base_url('ui')}}">User Interface</a></li>
                <li class="nav-item"><a class="nav-link" href="{{base_url('multipurpose')}}">Multipurpose</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a class="nav-link" href="https://gitbook.com/@o2system"><i class="fas fa-file-text"></i> Documentation</a></li>
            </ul>
        </div>
    </div>
</nav>