<nav id="page-navigation" class="navbar navbar-expand-md navbar-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="./assets/img/logo/logo-white-50px.png" height="50">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="<?php echo base_url(); ?>">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="<?php echo base_url('about'); ?>">About </a>
                </li>
            </ul>
            <ul class="navbar-nav navbar-right ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo base_url('ui'); ?>">
                        User Interface
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo base_url('multipurpose'); ?>">
                        Multipurpose
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="https://o2system.gitbook.io">
                        Documentation
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>