<nav id="page-navigation" class="navbar navbar-expand-md navbar-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="./assets/img/logo/logo-white-50px.png" height="50">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="<?php echo base_url(); ?>">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="<?php echo base_url('testing'); ?>" id="dropdown-testing" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Testing</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown-testing">
                        <a class="dropdown-item" href="<?php echo base_url('testing/cache'); ?>">Cache</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/curl'); ?>">Curl</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/database'); ?>">Database</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/email'); ?>">Email</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/filesystem'); ?>">Filesystem</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/gear'); ?>">Gear</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/helpers'); ?>">Helpers</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/html'); ?>">Html</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/image'); ?>">Image</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/libraries'); ?>">Libraries</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/parser'); ?>">Parser</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/security'); ?>">Security</a>
                        <a class="dropdown-item" href="<?php echo base_url('testing/session'); ?>">Session</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav navbar-right ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo base_url('ui'); ?>">
                        User Interface
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="https://o2system.gitbook.io">
                        Documentation
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>