<!-- Sidebar scroll-->
<div class="sidebar-scroll">
    <div class="account-cover" style="background-image:url({{$account->profile->images->cover}})">
        <div class="account-cover-avatar">
            <a href="{{base_url('personal/profile')}}"> <img src="assets/img/herlambang.jpg" alt="{{$account->profile->name->display}}"> </a>
        </div>
        <div class="account-cover-name">
            <a href="{{base_url('personal/profile')}}"><!-- {{$account->profile->name->display}} --> Herlambang S.</a>
            <small>
                <a href="{{base_url('personal/profile')}}">{{$account->roles->primary()}}</a>
            </small>
        </div>
    </div>

    <!-- Sidebar navigation-->
    <nav class="sidebar-nav">
        <ul id="sidebar-navigation">
            <li class="active">
                <a href="{{base_url}}" class="active">
                    <i class="fa fa-dashboard"></i>
                    <span class="hide-menu"> Dashboard </span>
                </a>
            </li>
            <li>
                <a href="{{base_url('personal')}}" class="has-arrow" aria-expanded="false">
                    <i class="fa fa-user"></i> <span class="hide-menu"> Personal </span>
                </a>
                <ul aria-expanded="false" class="collapse">
                    <li>
                        <a href="{{base_url('personal/profile')}}">
                            Profile
                        </a>
                        <a href="{{base_url('personal/contacts')}}">
                            Contacts
                        </a>
                        <a href="{{base_url('personal/attendance')}}">
                            Attendance
                        </a>
                        <a href="{{base_url('personal/activity')}}">
                            Activity
                        </a>
                        <a href="{{base_url('personal/career')}}">
                            Career
                        </a>
                        <a href="{{base_url('personal/agenda')}}">
                            Agenda
                        </a>
                        <a href="{{base_url('personal/notes')}}">
                            Notes
                        </a>
                        <a href="{{base_url('personal/tasks')}}">
                            Tasks
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="{{base_url('company')}}" class="has-arrow" aria-expanded="false">
                    <i class="fa fa-building"></i>
                    <span class="hide-menu"> Company </span>
                </a>
                <ul aria-expanded="false" class="collapse">
                    <li>
                        <a href="{{base_url('company/about')}}">
                            About
                        </a>
                        <a href="{{base_url('company/banks')}}">
                            Banks
                        </a>
                        <a href="{{base_url('company/departments')}}">
                            Departments
                        </a>
                        <a href="{{base_url('company/events')}}">
                            Events
                        </a>
                        <a href="{{base_url('company/internal-memo')}}">
                            Internal Memo
                        </a>
                        <a href="{{base_url('company/meetings')}}">
                            Meetings
                        </a>
                        <a href="{{base_url('company/news')}}">
                            News
                        </a>
                        <a href="{{base_url('company/structure')}}">
                            Structure
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="{{base_url('units')}}" class="has-arrow" aria-expanded="false">
                    <i class="fa fa-building-o"></i>
                    <span class="hide-menu"> Units </span>
                </a>
                <ul aria-expanded="false" class="collapse">
                    <li>
                        <a href="{{base_url('units/manage')}}">
                            Manage
                        </a>
                        <a href="{{base_url('units/sections')}}">
                            Sections
                        </a>
                        <a href="{{base_url('units/types')}}">
                            Types
                        </a>
                        <a href="{{base_url('units/categories')}}">
                            Categories
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="{{base_url('finance')}}" class="has-arrow" aria-expanded="false">
                    <i class="fa fa-money"></i>
                    <span class="hide-menu"> Finance </span>
                </a>
                <ul aria-expanded="false" class="collapse">
                    <li>
                        <a href="{{base_url('finance')}}">
                            Dashboard
                        </a>
                        <a href="{{base_url('finance/statements')}}">
                            Statements
                        </a>
                        <a href="{{base_url('finance/journals')}}">
                            Journals
                        </a>
                        <a href="{{base_url('finance/chart-of-account')}}">
                            Chart of Account
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="{{base_url('administrator')}}" class="has-arrow" aria-expanded="false">
                    <i class="fa fa-users"></i>
                    <span class="hide-menu"> Administrator </span>
                </a>
                <ul aria-expanded="false" class="collapse">
                    <li>
                        <a href="{{base_url('administrator/users')}}" class="has-arrow" aria-expanded="false">
                            Users
                        </a>
                        <ul aria-expanded="false" class="collapse" id="users-sub-navigation">
                            <li>
                                <a href="{{base_url('administrator/users/manage')}}">Manage</a>
                            </li>
                            <li>
                                <a href="{{base_url('administrator/users/roles')}}">Roles</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{{base_url('administrator/modules')}}" class="has-arrow" aria-expanded="false">
                            Modules
                        </a>
                        <ul aria-expanded="false" class="collapse" id="users-sub-navigation">
                            <li>
                                <a href="{{base_url('administrator/modules/manage')}}">Manage</a>
                            </li>
                            <li>
                                <a href="{{base_url('administrator/modules/installer')}}">Installer</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <!-- End Sidebar navigation -->
</div>
<!-- End Sidebar scroll-->