<div class="jumbotron jumbotron-bg rounded-0 mb-0 vertical-center text-center" style="background-image: url('assets/img/bg-galaxy.jpg');">
    <div class="container">
        <img src="./assets/img/logo/logo-white-200px.png" style="margin: 50px 0px" class="logo">
        <h1 class="display-4 text-uppercase">
            O2System Framework
        </h1>
        <p class="lead text-uppercase">
            The Next Generation of PHP Framework<br>
        </p>
        <p>
            Built for developers who need ease, cleverness, elegance codes and user interface to build fully featured web applications.
        </p>
    </div>
</div>

<section id="features" class="section-basic gray-bg">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center mb-3">
                <h1 class="title">Features</h1>
                </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-right" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary fab fa-superpowers"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">Superpower</a></h6>
                                <p class="mt-3">Enhanced with a variety of very powerful php class libraries.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-down" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary fas fa-bolt"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">Lightest and Fastest</a></h6>
                                <p class="mt-3">Produce results at high speed with very small memory consumption.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-left" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary fas fa-lightbulb"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">100% Satisfaction </a></h6>
                                <p class="mt-3">A very clever framework with smart routing system.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-right" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary fas fa-shield-alt"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">Invulnerable</a></h6>
                                <p class="mt-3">Reinforced with many security classes to build secure applications.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-up" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary fas fa-code"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">Elegant</a></h6>
                                <p class="mt-3">Written with expressive and beautiful syntax.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="feature5-box">
                    <div class="card card-shadow border-0 mb-5" data-aos="fade-left" data-aos-duration="1200">
                        <div class="card-body d-flex">
                            <div class="feature-icon-space"><i class="text-primary  fas fa-paint-brush"></i></div>
                            <div class="">
                                <h6 class="font-weight-normal"><a href="javascript:void(0)" class="link">User Interface</a></h6>
                                <p class="mt-3">Enriched with built-in ui theme and generator.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="desc" class="section-basic">
    <div class="container">
        <h2 class="section-basic-heading">Rapid Application Development</h2>
        <p class="section-basic-lead">
            Built any php-applications at wrap speed with our boiler-plates.
        </p>

        <div class="jumbotron gray-bg">
            <div class="row">
                <div class="col">
                    <h1 class="display-4">
                        Basic
                    </h1>
                    <p class="lead">
                        For those who likes to make everything from scratch, build your project with this boilerplate.
                    </p>
                    <hr>
                    <p>
                        The easiest way is to use the composer command
                    </p>

                    <pre class="line-numbers rounded"><code>composer create-project o2system/o2system</code></pre>

                    <p class="lead mt-3">
                        <a href="#" class="btn btn-dark btn-md">
                            <i class="fab fa-github"></i>
                            View on Github
                        </a>
                    </p>
                </div>
                <div class="col text-center">
                    <img src="assets/img/hello/basic-boilerplate.png">
                </div>
            </div>

        </div>

        <div class="row mt-3">
            <div class="col-md-4">
                <div class="feature7-box">
                    <div class="" data-aos="flip-left" data-aos-duration="1200">
                        <img class="rounded img-fluid" src="assets/img/hello/api-boilerplate.jpg" alt="Infinite Multipurpose" />
                        <div class="mt-3">
                            <h5 class="font-weight-normal">Restful Service</h5>
                            <p class="mt-3">
                                If you need to build a API restful service, you can start building it with this boilerplate.
                            </p>

                            <pre><code>composer create-project o2system/webrestful</code></pre>

                            <p class="card-link mt-3">
                                <a href="https://github.com/o2system/webrestful" class="btn btn-dark btn-md">
                                    <i class="fab fa-github"></i>
                                    View on Github
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="feature7-box">
                    <div class="" data-aos="flip-up" data-aos-duration="1200">
                        <img class="rounded img-fluid" src="assets/img/hello/app-boilerplate.jpg" alt="Infinite Multipurpose" />
                        <div class="mt-3">
                            <h5 class="font-weight-normal">Cli Application</h5>
                            <p class="mt-3">
                                If you need to build a command line interface (CLI) application, you can start building it with this boilerplate.
                            </p>
                            <pre><code>composer create-project o2system/webcli</code></pre>

                            <p class="card-link mt-3">
                                <a href="https://github.com/o2system/webcli" class="btn btn-dark btn-md">
                                    <i class="fab fa-github"></i>
                                    View on Github
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="feature7-box">
                    <div class="" data-aos="flip-right" data-aos-duration="1200">
                        <img class="rounded img-fluid" src="assets/img/hello/app-boilerplate.jpg" alt="Infinite Multipurpose" />
                        <div class="mt-3">
                            <h5 class="font-weight-normal">Web Application</h5>
                            <p class="mt-3">
                                If you need to build a web-based application, you can start building it with this boilerplate.
                            </p>
                            <pre><code>composer create-project o2system/webapp</code></pre>

                            <p class="card-link mt-3">
                                <a href="https://github.com/o2system/webapp" class="btn btn-dark btn-md">
                                    <i class="fab fa-github"></i>
                                    View on Github
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>