<div class="welcome">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <img src="./assets/img/logo/logo-200px.png" alt="O2System Framework">
                <h1 class="text-uppercase mt-3 mb-0">
                    O2System Framework
                </h1>
                <p class="lead text-uppercase mb-2">
                    The Next Generation of PHP Framework<br>
                </p>
                <p>
                    Built for developers who need ease, cleverness, elegance codes 
                    and user interface to build fully featured web applications.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ul class="nav-bottom">
                    <li>
                        <a href="https://github.com/o2system" target="_blank">
                            <i class="fab fa-github"></i>
                            Github
                    </a>
                    </li>
                    <li>
                        <a href="https://o2system.gitbooks.io" target="_blank">
                            <i class="fas fa-book"></i>
                            GitBook
                    </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>