<div class="jumbotron jumbotron-bg rounded-0 mb-0 vertical-center text-center" style="background-image: url('assets/img/bg-galaxy.jpg');">
    <div class="container">
        <img src="./assets/img/logo/logo-white-200px.png" style="margin: 50px 0px" class="logo">
        <h1 class="display-4 text-uppercase">
            O2System Framework
        </h1>
        <p class="lead text-uppercase">
            The Next Generation of PHP Framework<br>
        </p>
        <p>
            Built for developers who need ease, cleverness, elegance codes and user interface to build fully featured web applications.
        </p>
    </div>
</div>

<section id="features" class="section-basic gray-bg">
    <div class="container">

        <div class="row text-center">

            <!-- Item -->
            <div class="item col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.4s">
                <div class="card border-0 mb-5">
                    <div class="card-icon">
                        <div class="card-icon-i">
                            <i class="fa fa-superpowers"></i>
                        </div>
                    </div>
                    <div class="card-body pb-5">
                        <h4 class="card-title">
                            Superpower
                        </h4>
                        <p class="card-text">
                            Enhanced with a variety of very powerful php class libraries.
                        </p>
                    </div>
                </div>
            </div>
            <!-- End Item -->

            <!-- Item -->
            <div class="item col-lg-4 col-md-6 wow fadeInUp">
                <div class="card border-0 mb-5">
                    <div class="card-icon">
                        <div class="card-icon-i">
                            <i class="fa fa-bolt"></i>
                        </div>
                    </div>
                    <div class="card-body pb-5">
                        <h4 class="card-title">
                            Lightest and Fastest
                        </h4>
                        <p class="card-text">
                            Produce results at high speed with very small memory consumption.
                        </p>
                    </div>
                </div>
            </div>
            <!-- End Item -->

            <!-- Item -->
            <div class="item col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
                <div class="card border-0 mb-5">
                    <div class="card-icon">
                        <div class="card-icon-i">
                            <i class="fa fa-ravelry"></i>
                        </div>
                    </div>
                    <div class="card-body pb-5">
                        <h4 class="card-title">
                            Intelligence
                        </h4>
                        <p class="card-text">
                            A very clever framework with smart routing system.
                        </p>
                    </div>
                </div>
            </div>
            <!-- End Item -->


            <!-- Item -->
            <div class="item col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.6s">
                <div class="card border-0 mb-5">
                    <div class="card-icon">
                        <div class="card-icon-i">
                            <i class="fa fa-shield"></i>
                        </div>
                    </div>
                    <div class="card-body pb-5">
                        <h4 class="card-title">
                            Invulnerable
                        </h4>
                        <p class="card-text">
                            Reinforced with many security classes to build secure applications.
                        </p>
                    </div>
                </div>
            </div>
            <!-- End Item -->

            <!-- Item -->
            <div class="item col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.8s">
                <div class="card border-0 mb-5">
                    <div class="card-icon">
                        <div class="card-icon-i">
                            <i class="fa fa-code"></i>
                        </div>
                    </div>
                    <div class="card-body pb-5">
                        <h4 class="card-title">
                            Elegant
                        </h4>
                        <p class="card-text">
                            Written with expressive and beautiful syntax.
                        </p>
                    </div>
                </div>
            </div>
            <!-- End Item -->

            <!-- Item -->
            <div class="item col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="1s">
                <div class="card border-0 mb-5">
                    <div class="card-icon">
                        <div class="card-icon-i">
                            <i class="fa fa-paint-brush"></i>
                        </div>
                    </div>
                    <div class="card-body pb-5">
                        <h4 class="card-title">
                            User Interface
                        </h4>
                        <p class="card-text">
                            Enriched with built-in ui theme and generator.
                        </p>
                    </div>
                </div>
            </div>
            <!-- End Item -->
        </div>

    </div>
</section>

<section id="desc" class="section-basic">
    <div class="container">
        <h2 class="section-basic-heading">Rapid Application Development</h2>
        <p class="section-basic-lead">
            Built any php-applications at wrap speed with our boiler-plates.
        </p>

        <div class="jumbotron gray-bg">
            <div class="row">
                <div class="col">
                    <h1 class="display-4">
                        Basic
                    </h1>
                    <p class="lead">
                        For those who likes to make everything from scratch, build your project with this boilerplate.
                    </p>
                    <hr>
                    <p>
                        The easiest way is to use the composer command
                    </p>

                    <pre class="line-numbers rounded"><code>composer create-project o2system/o2system</code></pre>

                    <p class="lead mt-3">
                        <a href="#" class="btn btn-dark btn-md">
                            <i class="fa fa-github"></i>
                            View on Github
                        </a>
                    </p>
                </div>
                <div class="col text-center">
                    <img src="assets/img/hello/basic-boilerplate.png">
                </div>
            </div>

        </div>

        <div class="row mt-5">
            <div class="col-md-4">
                <div class="card card-outline-default mb-5">
                    <img src="assets/img/hello/app-boilerplate.jpg" alt="Card image 2" class="card-img-top">
                    <div class="card-body">
                        <h4 class="card-title">
                            Web-Based App
                        </h4>
                        <p class="card-text">
                            If you need to build a website-based app, you can start building it using this boilerplate.
                        </p>

                        <pre><code>composer create-project o2system/web-app</code></pre>

                        <p class="card-link mt-3">
                            <a href="#" class="btn btn-dark btn-md">
                                <i class="fa fa-github"></i>
                                View on Github
                            </a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card card-outline-default mb-5">
                    <img src="assets/img/hello/cms-boilerplate.jpg" alt="Card image 3" class="card-img-top">
                    <div class="card-body">
                        <h4 class="card-title">
                            Website + CMS
                        </h4>
                        <p class="card-text">
                            If you need to build a website with cms, you can start building it by using this boilerplate.
                        </p>

                        <pre><code>composer create-project o2system/web-cms</code></pre>

                        <p class="card-link mt-3">
                            <a href="#" class="btn btn-dark btn-md">
                                <i class="fa fa-github"></i>
                                View on Github
                            </a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card card-outline-default mb-5">
                    <img src="assets/img/hello/api-boilerplate.jpg" alt="Card image 4" class="card-img-top">
                    <div class="card-body">
                        <h4 class="card-title">
                            Web-Based Service
                        </h4>
                        <p class="card-text">
                            If you need to build a website-based service, you can start building it with this boilerplate.
                        </p>

                        <p class="card-code">
                            <pre><code>composer create-project o2system/web-service</code></pre>
                        </p>

                        <p class="card-link mt-3">
                            <a href="#" class="btn btn-dark btn-md">
                                <i class="fa fa-github"></i>
                                View on Github
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>