<div class="static-slider static-slider-type-1" style="background-image:url(assets/img/multipurpose/bg-color.jpg)">
    <div class="container">
        <!-- Row  -->
        <div class="row justify-content-center ">
            
            <div class="col-md-8 align-self-center text-center" data-aos="fade-right" data-aos-duration="1200">
                <h1 class="title text-light text-uppercase typewrite" data-period="2000" data-type='[ "Infinite", "Multipurpose" ]'></h1>
                <h5 class="text-light font-weight-normal">With Infinite Multipurpose, you can create everything, weather its Landing page, Complete Website, Lead generation or Coming soon etc.</h5>
                <a class="btn btn-primary btn-lg mt-3" href="#demos">Explore Demos</a>
            </div>
        </div>
    </div>
</div>

<div class="bg-primary">
    <div class="container">
        <div class="row text-center counter-box">
            <div class="col-lg-3 col-6" data-aos="fade-right" data-aos-duration="1200">
                <div class="">
                    <h2 class="text-white mb-0"><span class="counter">150</span>+</h2>
                    <h6 class="text-white">Interface Sections <br/>Ready to Use</h6>
                </div>
            </div>
            <div class="col-lg-3 col-6" data-aos="fade-up" data-aos-duration="1200">
                <div class="">
                    <h2 class="text-white mb-0"><span class="counter">25</span>+</h2>
                    <h6 class="text-white">Amazing Pre-Built <br/>Niche Demos</h6>
                </div>
            </div>
            <div class="col-lg-3 col-6" data-aos="fade-up" data-aos-duration="1200">
                <div class="">
                    <h2 class="text-white mb-0"><span class="counter">500</span>+</h2>
                    <h6 class="text-white">Useful Elements &amp; <br/>Page Templates</h6>
                </div>
            </div>
            <div class="col-lg-3 col-6" data-aos="fade-left" data-aos-duration="1200">
                <div class="">
                    <h2 class="text-white mb-0"><span class="counter">3000</span>+</h2>
                    <h6 class="text-white">Premium Font Icons <br/>worth $79 Free</h6>
                </div>
            </div>
        </div>
    </div>
</div>

<section id="demos">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h1 class="title">Demos from Infinite Multipurpose</h1>
                <h6 class="subtitle">Here you can check Demos we created based on Infinite Multipurpose. Its quite easy to Create your own dream website &amp; dashboard in No-time.</h6>
            </div>
        </div>
        <div class="row text-center mt-5">
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-left" data-aos-duration="1200">
                    <a href="../all-demos/demo-creative/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/1.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Creative Demo</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-up" data-aos-duration="1200">
                    <a href="../all-demos/demo-business/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/2.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Business &amp; Corporate</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-up" data-aos-duration="1200">
                    <a href="../all-demos/demo-cryptocurrency/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/24.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Cryptocurrency</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-right" data-aos-duration="1200">
                    <a href="../all-demos/demo-software-application/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/3.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Software Application</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-left" data-aos-duration="1200">
                    <a href="../all-demos/demo-charity/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/4.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Charity Demo</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-up" data-aos-duration="1200">
                    <a href="../all-demos/demo-web-agency/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/5.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Web Agency</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-right" data-aos-duration="1200">
                    <a href="../all-demos/demo-medical/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/6.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Health &amp; Medical</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-left" data-aos-duration="1200">
                    <a href="../all-demos/demo-real-estate/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/7.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Real Estate</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-up" data-aos-duration="1200">
                    <a href="../all-demos/demo-restaurant/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/8.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Restaurant Demo</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-right" data-aos-duration="1200">
                    <a href="../all-demos/demo-landingpage-app/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/9.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>App Landingpage</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-left" data-aos-duration="1200">
                    <a href="../all-demos/demo-fitness/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/10.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Fitness Demo</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-up" data-aos-duration="1200">
                    <a href="../all-demos/demo-landingpage-medical/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/11.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Health &amp; Medical Landingpage</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-right" data-aos-duration="1200">
                    <a href="../all-demos/demo-marketing-seo/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/12.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Marketing Seo</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-left" data-aos-duration="1200">
                    <a href="../all-demos/demo-accounting/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/13.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Accounting Demo</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-up" data-aos-duration="1200">
                    <a href="../all-demos/demo-onepage/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/14.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>One page Demo</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-right" data-aos-duration="1200">
                    <a href="../all-demos/demo-industrial/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/15.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Industrial Demo</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-left" data-aos-duration="1200">
                    <a href="../all-demos/demo-photography2/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/16.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Photography Dark</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-up" data-aos-duration="1200">
                    <a href="../all-demos/demo-landingpage-personal/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/17.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Personal Landingpage</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-right" data-aos-duration="1200">
                    <a href="../all-demos/demo-landingpage-appointment/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/18.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Appointment Landingpage</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-left" data-aos-duration="1200">
                    <a href="../all-demos/demo-freelancer1/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/19.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Freelancer Demo</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-up" data-aos-duration="1200">
                    <a href="../all-demos/demo-landingpage-form/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/20.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Form Landingpage</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-right" data-aos-duration="1200">
                    <a href="../all-demos/demo-freelancer2/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/21.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Freelancer2 Demo</h6>
                </div>
            </div>
            
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-right" data-aos-duration="1200">
                    <a href="../all-demos/demo-photography1/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/23.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Photography Light</h6>
                </div>
            </div>
            
            <div class="col-md-4 mt-2 mb-3">
                <div class="card" data-aos="flip-left" data-aos-duration="1200">
                    <a href="../all-demos/demo-coming-soon/index.html" target="_blank">
                        <img class="card-img-top" src="../assets/images/innerpage/demos/22.jpg" alt="Infinite Multipurpose">
                    </a>
                </div>
                <div class="pt-3">
                    <h6>Comming Soon Page</h6>
                </div>
            </div>
            
            <div class="text-center w-100"><strong>More Demos Comming soon...</strong></div>
        </div>
    </div>
</section>

<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h1 class="title">We have covered you Quite Well</h1>
                <h6 class="subtitle">There are several reasons you will love the Infinite Multipurpose, we have listed some of them here, check them out.</h6>
            </div>
        </div>
        <div class="row mt-5 text-center">
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fas fa-desktop"></i></h1>
                <h6>Bootstrap 4 <br>Toolkit</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fab fa-google-drive"></i></h1>
                <h6>Google <br>Fonts</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fas fa-futbol fa-spin"></i></h1>
                <h6>Animate <br>CSS</h6>
            </div>

            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fas fa-gift"></i></h1>
                <h6>Premium <br>Icons</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fas fa-bars"></i></h1>
                <h6>Bootstrap <br>Nav</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fas fa-eye"></i></h1>
                <h6>Ratina <br>Ready</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fas fa-paint-brush"></i></h1>
                <h6>Modern &amp;<br>vibrant design</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fas fa-code"></i></h1>
                <h6>W3C <br>Validation</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fas fa-fighter-jet"></i></h1>
                <h6>Speed <br>Optimized</h6>
            </div>

            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fas fa-file-alt"></i></h1>
                <h6>Detailed <br>Documentation</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="fas fa-mobile"></i></h1>
                <h6>Responsive <br>Layout</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h1 class="text-primary"><i class="far fa-smile"></i></h1>
                <h6>Easy to<br>Maintain</h6>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h1 class="title">Infinite Possibilities</h1>
                <h6 class="subtitle">With Infinite Multipurpose, you can create everything, weather its Landing page, Complete Website, Lead generation or Coming soon etc.</h6>
            </div>
        </div>
        <div class="row text-center mt-5 counter-box-dark">
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h2 class="mb-0 text-primary"><span class="counter">20</span>+</h2>
                <h6 class="font-14 op-7">Headers &amp;<br>Footers</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h2 class="mb-0 text-primary"><span class="counter">40</span>+</h2>
                <h6 class="font-14 op-7">Banners, Sliders <br>and Forms</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h2 class="mb-0 text-primary"><span class="counter">60</span>+</h2>
                <h6 class="font-14 op-7">Feautes, Modals &amp;<br>Content Blocks</h6>
            </div>
            
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h2 class="mb-0 text-primary"><span class="counter">15</span>+</h2>
                <h6 class="font-14 op-7">Portfolio &amp; <br>Teams</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h2 class="mb-0 text-primary"><span class="counter">18</span>+</h2>
                <h6 class="font-14 op-7">Pricing Tables &amp;<br>Testimonials</h6>
            </div>
            <div class="col-lg-2 col-md-4 col-6 mb-3 mt-2">
                <h2 class="mb-0 text-primary"><span class="counter">25</span>+</h2>
                <h6 class="font-14 op-7">Blog, Call 2 Action <br>&amp; Contact Us</h6>
            </div>
        </div>
    </div>
    <!-- Slider -->
    <div class="owl-carousel owl-theme image-slide mt-5">
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/1.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/2.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/3.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/4.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/5.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/6.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/7.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/8.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/9.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/10.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/11.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/12.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/13.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/14.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/15.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/16.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/17.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/18.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/19.jpg" alt="Infinite Multipurpose" />
        </div>
        <div class="item">
            <img src="../assets/images/innerpage/img-slide/20.jpg" alt="Infinite Multipurpose" />
        </div>
    </div>
    <!-- Slider -->
</section>

<section class="bg-gray">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h1 class="title">Are you happy with what we offer? <br>Enjoy Infinite Multipurpose Now!</h1>
                <h6 class="subtitle">150+ Ready to Use Sections, 25+ Pre-Build Demos, 500+ UI Elements and lots more.</h6>
                <div class="mt-5">
                    <a class="btn btn-primary btn-lg" href="#demos">Get Started</a>
                </div>
            </div>
        </div>
    </div>
</section>