<nav class="navbar top-navbar navbar-expand-md navbar-light">
    <!-- Logo -->
    <a class="navbar-brand" href="{{base_url()}}">
        <img src="./assets/img/logo/logo-50px.png" alt="logo" />
    </a>
    <!-- End Logo -->
    <div class="navbar-collapse">
        <!-- toggle and nav items -->
        <ul class="navbar-nav mr-auto mt-md-0 ">
            <!-- This is  -->
            <li class="nav-item">
                <a class="nav-link nav-toggler d-md-none d-block text-muted" href="javascript:void(0)"><i class="fa fa-bars"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link sidebartoggler d-none d-md-none text-muted" href="javascript:void(0)"><i class="fa fa-bars"></i></a>
            </li>
            <!-- Notif -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-muted" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-bell-o"></i>
                    <div class="notify"> <span class="heartbit"></span> <span class="point"></span> </div>
                </a>
                <div class="dropdown-menu dropdown-menu mailbox">
                    <ul>
                        <li>
                            <div class="drop-title">Notifications <span class="badge badge-danger">5 New</span></div>
                        </li>
                        <li>
                            <div class="message-center">
                                <!-- Message -->
                                <a href="#">
                                    <div class="btn btn-danger btn-circle"><i class="fa fa-link"></i></div>
                                    <div class="mail-content">
                                        <h5>Luanch Admin</h5>
                                        <span class="mail-desc">Just see the my new admin!</span>
                                        <span class="time">9:30 AM</span>
                                    </div>
                                </a>
                                <!-- Message -->
                                <a href="#">
                                    <div class="btn btn-success btn-circle"><i class="fa fa-calendar"></i></div>
                                    <div class="mail-content">
                                        <h5>Event today</h5>
                                        <span class="mail-desc">Just a reminder that you have event</span>
                                        <span class="time">9:10 AM</span>
                                    </div>
                                </a>
                            </div>
                        </li>
                        <li>
                            <a class="nav-link text-center" href="javascript:void(0);"> <strong>Check all notifications</strong> <i class="fa fa-angle-right"></i> </a>
                        </li>
                    </ul>
                </div>
            </li>
            <!-- End Notif -->
            <!-- Messages -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-muted" href="#" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-envelope-o"></i>
                    <div class="notify"> <span class="heartbit"></span> <span class="point"></span> </div>
                </a>
                <div class="dropdown-menu dropdown-menu mailbox" aria-labelledby="2">
                    <ul>
                        <li>
                            <div class="drop-title">Messages <span class="badge badge-danger">5 New</span></div>
                        </li>
                        <li>
                            <div class="message-center">
                                <!-- Message -->
                                <a href="#">
                                    <div class="user-img">
                                        <img src="assets/img/avatar.jpg" alt="user" class="img-circle">
                                        <span class="profile-status online pull-right"></span>
                                    </div>
                                    <div class="mail-content">
                                        <h5>Pavan kumar</h5>
                                        <span class="mail-desc">Just see the my admin!</span>
                                        <span class="time">9:30 AM</span>
                                    </div>
                                </a>
                                <!-- Message -->
                                <a href="#">
                                    <div class="user-img">
                                        <img src="{{$account->profile->images->avatar}}" alt="{{$account->profile->name->display}}" class="img-circle">
                                        <span class="profile-status busy pull-right"></span>
                                    </div>
                                    <div class="mail-content">
                                        <h5>Sonu Nigam</h5>
                                        <span class="mail-desc">I've sung a song! See you at</span>
                                        <span class="time">9:10 AM</span>
                                    </div>
                                </a>
                            </div>
                        </li>
                        <li>
                            <a class="nav-link text-center" href="javascript:void(0);"> <strong>See all e-Mails</strong> <i class="fa fa-angle-right"></i> </a>
                        </li>
                    </ul>
                </div>
            </li>
            <!-- End Messages -->
        </ul>
        <!-- User profile -->
        <ul class="navbar-nav my-lg-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-muted" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="{{$account->profile->images->avatar}}" alt="{{$account->profile->name->display}}" class="profile-pic" />
                </a>
                <div class="dropdown-menu dropdown-menu-right py-0">
                    <ul class="dropdown-account">
                        <li>
                            <div class="account-cover rounded-top" style="background-image:url({{$account->profile->images->cover}})">
                                <div class="account-cover-avatar">
                                    <a href="{{base_url('personal/profile')}}"> <img src="{{$account->profile->images->avatar}}" alt="{{$account->profile->name->display}}"> </a>
                                </div>
                                <div class="account-cover-name">
                                    <a href="{{base_url('personal/profile')}}">{{$account->profile->name->display}}</a>
                                    <small>
                                        <a href="{{base_url('personal/profile')}}">{{$account->roles->primary()}}</a>
                                    </small>
                                </div>
                            </div>
                        </li>
                        <li><a href="{{base_url('personal/setting')}}"><i class="fa fa-cogs"></i> Setting</a></li>
                        <li><a href="{{base_url('logout')}}"><i class="fa fa-power-off"></i> Logout</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</nav>