<nav class="navbar top-navbar navbar-expand-md navbar-light">
    <!-- Logo -->
    <a class="navbar-brand" href="{{base_url()}}">
        <img src="./assets/img/logo/logo-50px.png" alt="logo" />
    </a>
    <a class="navbar-brand text-muted" href="{{base_url()}}">
        Close
    </a>
    <!-- End Logo -->
    <div class="navbar-collapse">
        <!-- toggle and nav items -->
        <ul class="navbar-nav mr-auto mt-md-0 ">
            <!-- This is  -->
            <li class="nav-item">
                <a class="nav-link nav-toggler d-md-none d-block text-muted" href="javascript:void(0)"><i class="fa fa-cog"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link sidebartoggler d-none d-md-none text-muted" href="javascript:void(0)"><i class="fa fa-cog"></i></a>
            </li>
        </ul>
        <!-- User profile -->
        <ul class="navbar-nav my-lg-0">
            <li class="nav-item">
                <a class="btn btn-default mr-2" href="javascript:void(0)">Preview</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-primary" href="javascript:void(0)">Publish</a>
            </li>
        </ul>
    </div>
</nav>