<div class="sidebar-scroll">
	<div class="card">
	    <div class="card-header">
	        Category
	    </div>
	    <div class="card-body">
	        <div class="form-group row">
	            <label class="col-md-12">Master</label>
	            <div class="col-md-12">
	                <select class="form-control custom-select">
	                    <option value="">Otomotif </option>
	                    <option value="">Fashion </option>
	                </select>
	            </div>
	        </div>
	        <div class="form-group row">
	            <label class="col-md-12">User Defined</label>
	            <div class="col-md-12">
	                <select class="form-control custom-select">
	                    <option value="">Otomotif </option>
	                    <option value="">Fashion </option>
	                </select>
	            </div>
	        </div>
	    </div>
	</div>
	<div class="card">
	    <div class="card-header">
	        Brand

	    </div>
	    <div class="card-body">
	        <div class="form-group row">
	            <div class="col-md-12">
	                <select class="form-control custom-select">
	                    <option value="">Otomotif </option>
	                    <option value="">Fashion </option>
	                </select>
	            </div>
	        </div>
	    </div>
	</div>
	<div class="card">
	    <div class="card-header">
	        Price
	    </div>
	    <div class="card-body">
	        <div class="form-group row">
	            <div class="col-md-12">
	                <div class="input-group">
	                    <span class="input-group-addon">Rp.</span>
	                    <input id="product-price" name="price" placeholder="10000" class="form-control input-md required" required="" value="" type="text">
	                </div>
	            </div>
	        </div>
	        <div class="form-group row">
	            <label class="col-md-12">Discount</label>
	            <div class="col-md-12">
	                <select class="form-control custom-select">
	                    <option value="">Select discount type</option>
	                </select>
	            </div>
	        </div>
	    </div>
	</div>
	<div class="card">
	    <div class="card-header">
	        Attribute
	    </div>
	    <div class="card-body">
	        <div class="form-group row">
	            <label class="col-md-12">Condition</label>
	            <div class="col-md-12">
	                <select class="form-control custom-select">
	                    <option value="">New </option>
	                    <option value="">Second </option>
	                </select>
	            </div>
	        </div>
	        <div class="form-group row">
	            <label class="col-md-12">Available for order online?</label>
	            <div class="col-md-12">
	                <select class="form-control custom-select">
	                    <option value="">Yes </option>
	                    <option value="">No </option>
	                </select>
	            </div>
	        </div>
	    </div>
	</div>
</div>