<!-- Sidebar scroll-->
<div class="sidebar-scroll">
    <!-- Sidebar navigation-->
    <nav class="sidebar-nav">
        <ul id="sidebar-navigation" class="in">
            {{$menus->main->items}}

            {{$menus->manage}}
            {{$menus->manage->items}}
            <li>
                <a href="{{base_url('products')}}"><i class="fa fa-cubes"></i> <span class="hide-menu"> Products </span> </a>
                <a href="{{base_url('products/form')}}" class="sidebar-button">Add</a>
            </li>

            {{$menus->personalize}}
            {{$menus->personalize->items}}

            {{$menus->configure}}
            {{$menus->configure->items}}
        </ul>
    </nav>
    <!-- End Sidebar navigation -->
</div>
<!-- End Sidebar scroll-->